#!/bin/bash

bitbake xf86-video-fbdev -c fetchall
bitbake xf86-video-imxfb-vivante.p8.6 -c fetchall
bitbake imx-gpu-viv.p8.6-hfp -c fetchall
bitbake udev-rules-imx -c fetchall
bitbake udev-rules-qoriq -c fetchall
bitbake fsl-pme -c fetchall
bitbake pme-tools -c fetchall
bitbake skmm-ep -c fetchall
bitbake merge-files -c fetchall
bitbake testfloata -c fetchall
bitbake ipc-ust -c fetchall
bitbake cantest -c fetchall
bitbake hyperrelay -c fetchall
bitbake restool -c fetchall
bitbake management-complex -c fetchall
bitbake dpl-examples -c fetchall
bitbake web-sysmon -c fetchall
bitbake fmc -c fetchall
bitbake usdpaa-apps -c fetchall
bitbake ipsec-demo -c fetchall
bitbake asf -c fetchall
bitbake fmlib -c fetchall
bitbake usdpaa -c fetchall
bitbake fm-ucode -c fetchall
bitbake eth-config -c fetchall
bitbake flib -c fetchall
bitbake dpa-offload -c fetchall
bitbake fsl-image-mfgtool-initramfs -c fetchall
bitbake packagegroup-fsl-mfgtool -c fetchall
bitbake openssl-qoriqh -c fetchall
bitbake ppa -c fetchall
bitbake imx-bootlets -c fetchall
bitbake imx-lib -c fetchall
bitbake imx-test -c fetchall
bitbake imx-test -c fetchall
bitbake apptrk -c fetchall
bitbake barebox -c fetchall
bitbake ls2-phy -c fetchall
bitbake imx-uuc -c fetchall
bitbake mxsldr -c fetchall
bitbake rcw -c fetchall
bitbake ls2-rcw -c fetchall
bitbake firmware-imx -c fetchall
bitbake boot-format -c fetchall
bitbake u-boot-fslc -c fetchall
bitbake u-boot-imx -c fetchall
bitbake u-boot-fslc-mxsboot -c fetchall
bitbake u-boot-qoriq -c fetchall
bitbake u-boot-imx-mfgtool -c fetchall
bitbake elftosb -c fetchall
bitbake pkc-firmware -c fetchall
bitbake fsl-tlu -c fetchall
bitbake imx-kobs -c fetchall
bitbake qe-ucode -c fetchall
bitbake change-file-endianess -c fetchall
bitbake imx-vpu -c fetchall
bitbake skmm-host -c fetchall
bitbake ceetm -c fetchall
bitbake pkc-host -c fetchall
bitbake cryptodev-qoriq-tests -c fetchall
bitbake cryptodev-qoriq-linux -c fetchall
bitbake cryptodev-qoriq-module -c fetchall
bitbake kernel-module-imx-gpu-viv.p8.6 -c fetchall
bitbake kernel-module-scatter-gather -c fetchall
bitbake kernel-module-ar -c fetchall
bitbake kernel-module-imx-gpu-viv.p8.6+fslc -c fetchall
bitbake kernel-module-ipc-multi -c fetchall
bitbake kernel-module-perf-qoriq -c fetchall
bitbake kernel-module-uio-seville -c fetchall
bitbake kernel-module-ls-debug -c fetchall
bitbake kernel-module-ipc-single -c fetchall
bitbake linux-imx -c fetchall
bitbake linux-qoriq -c fetchall
bitbake linux-fslc -c fetchall
bitbake linux-imx-mfgtool -c fetchall
bitbake linux-fslc -c fetchall
bitbake linux-fslc-imx-rt-2.0.x -c fetchall
bitbake linux-fslc-imx-2.0.x -c fetchall
bitbake hypervisor -c fetchall
bitbake mux-server -c fetchall
bitbake hv-cfg -c fetchall
bitbake gstreamer1.0-plugins-imx -c fetchall
bitbake imx-gst1.0-plugin -c fetchall
bitbake imx-alsa-plugins -c fetchall
bitbake imx-codec -c fetchall
bitbake libimxvpuapi -c fetchall
bitbake imx-vpuwrap -c fetchall
bitbake imx-parser -c fetchall
bitbake qemu-qoriq -c fetchall
bitbake cst -c fetchall
bitbake imx-usb-loader -c fetchall
bitbake devregs -c fetchall
bitbake imx-gpu-sdk -c fetchall
bitbake devil -c fetchall
bitbake fsl-rc-local -c fetchall
bitbake fsl-image-multimedia-full -c fetchall
bitbake fsl-image-multimedia -c fetchall
bitbake fsl-image-machine-test -c fetchall
bitbake packagegroup-fsl-gstreamer1.0-full -c fetchall
bitbake packagegroup-imx-tools-audio -c fetchall
bitbake packagegroup-fsl-tools-benchmark -c fetchall
bitbake packagegroup-fsl-tools-testapps -c fetchall
bitbake packagegroup-fsl-tools-gpu -c fetchall
bitbake packagegroup-fsl-tools-gpu-external -c fetchall
bitbake packagegroup-fsl-gstreamer1.0 -c fetchall
bitbake packagegroup-fsl-gstreamer1.0-commercial -c fetchall
bitbake xf86-video-imxfb-vivante.p0 -c fetchall
bitbake opencv -c fetchall
bitbake imx-gpu-g2d.p0 -c fetchall
bitbake glslang -c fetchall
bitbake spirv-tools -c fetchall
bitbake vulkan-samples -c fetchall
bitbake vulkan-tools -c fetchall
bitbake vulkan-loader-layers -c fetchall
bitbake imx-gpu-viv.p0-aarch32 -c fetchall
bitbake imx-gpu-apitrace -c fetchall
bitbake glm -c fetchall
bitbake systemd-gpuconfig -c fetchall
bitbake imx-lib -c fetchall
bitbake imx-test -c fetchall
bitbake imx-uuc -c fetchall
bitbake firmware-imx -c fetchall
bitbake u-boot-imx -c fetchall
bitbake u-boot-imx-mfgtool -c fetchall
bitbake imx-kobs -c fetchall
bitbake imx-vpu -c fetchall
bitbake linux-libc-headers -c fetchall
bitbake kernel-module-imx-gpu-viv.p0 -c fetchall
bitbake linux-imx -c fetchall
bitbake linux-imx-mfgtool -c fetchall
bitbake simg2img -c fetchall
bitbake gstreamer1.0-plugins-bad -c fetchall
bitbake gstreamer1.0-plugins-ugly -c fetchall
bitbake imx-gst1.0-plugin -c fetchall
bitbake gstreamer1.0-plugins-good -c fetchall
bitbake gstreamer1.0-rtsp-server -c fetchall
bitbake gstreamer1.0-plugins-base -c fetchall
bitbake gstreamer1.0-libav -c fetchall
bitbake gstreamer1.0 -c fetchall
bitbake imx-alsa-plugins -c fetchall
bitbake imx-codec -c fetchall
bitbake imx-vpuwrap -c fetchall
bitbake imx-parser -c fetchall
bitbake python-erpc -c fetchall
bitbake imx-gpu-sdk -c fetchall
bitbake assimp -c fetchall
bitbake gstreamer1.0-plugins-bad-qt -c fetchall
bitbake imx-qtapplications-aarch32 -c fetchall
bitbake packagegroup-fsl-tools-audio -c fetchall
bitbake packagegroup-qt5-webengine -c fetchall
bitbake packagegroup-qt5-demos -c fetchall
bitbake packagegroup-fsl-pulseaudio -c fetchall
bitbake packagegroup-imx-erpc -c fetchall
bitbake fsl-image-qt5 -c fetchall
bitbake fsl-image-validation-imx -c fetchall
bitbake fsl-image-gui -c fetchall
bitbake fsl-image-qt5-validation-imx -c fetchall
bitbake imx-m4-demos -c fetchall
bitbake imx-m4-demosulp-beta -c fetchall
bitbake selftest-recipetool-appendfile -c fetchall
bitbake emptytest -c fetchall
bitbake aspell -c fetchall
bitbake oe-selftest-image -c fetchall
bitbake wic-image-minimal -c fetchall
bitbake error-image -c fetchall
bitbake test-empty-image -c fetchall
bitbake error -c fetchall
bitbake devtool-upgrade-test1 -c fetchall
bitbake devtool-upgrade-test2 -c fetchall
bitbake linux-yocto-custom -c fetchall
bitbake example-recipe-0.1 -c fetchall
bitbake rng-tools -c fetchall
bitbake libunistring -c fetchall
bitbake debianutils -c fetchall
bitbake libgpg-error -c fetchall
bitbake npth -c fetchall
bitbake libpcre -c fetchall
bitbake libgcrypt -c fetchall
bitbake consolekit -c fetchall
bitbake lzo -c fetchall
bitbake gnome-desktop-testing -c fetchall
bitbake libcap -c fetchall
bitbake libcheck -c fetchall
bitbake nss -c fetchall
bitbake source-highlight -c fetchall
bitbake iso-codes -c fetchall
bitbake ptest-runner -c fetchall
bitbake libevdev -c fetchall
bitbake vte -c fetchall
bitbake popt -c fetchall
bitbake nspr -c fetchall
bitbake gnutls -c fetchall
bitbake libtasn1 -c fetchall
bitbake libatomic-ops -c fetchall
bitbake libksba -c fetchall
bitbake libxslt -c fetchall
bitbake mpfr -c fetchall
bitbake curl -c fetchall
bitbake serf -c fetchall
bitbake libdaemon -c fetchall
bitbake libexif -c fetchall
bitbake bmap-tools -c fetchall
bitbake p11-kit -c fetchall
bitbake taglib -c fetchall
bitbake lz4 -c fetchall
bitbake icu -c fetchall
bitbake createrepo -c fetchall
bitbake xuser-account -c fetchall
bitbake shared-mime-info -c fetchall
bitbake gpgme -c fetchall
bitbake libusb-compat -c fetchall
bitbake libusb1 -c fetchall
bitbake neon -c fetchall
bitbake ca-certificates -c fetchall
bitbake acl -c fetchall
bitbake attr -c fetchall
bitbake nettle -c fetchall
bitbake nettle -c fetchall
bitbake db -c fetchall
bitbake db -c fetchall
bitbake boost -c fetchall
bitbake bjam-native -c fetchall
bitbake gmp -c fetchall
bitbake gmp -c fetchall
bitbake libevent -c fetchall
bitbake lzop -c fetchall
bitbake bdwgc -c fetchall
bitbake libproxy -c fetchall
bitbake aspell -c fetchall
bitbake beecrypt -c fetchall
bitbake libcap-ng -c fetchall
bitbake bash-completion -c fetchall
bitbake sqlite3 -c fetchall
bitbake argp-standalone -c fetchall
bitbake gdbm -c fetchall
bitbake gdbm -c fetchall
bitbake libyaml -c fetchall
bitbake libical -c fetchall
bitbake libassuan -c fetchall
bitbake libcroco -c fetchall
bitbake gnupg -c fetchall
bitbake gnupg -c fetchall
bitbake libmpc -c fetchall
bitbake apr -c fetchall
bitbake apr-util -c fetchall
bitbake libunwind -c fetchall
bitbake at-spi2-core -c fetchall
bitbake at-spi2-atk -c fetchall
bitbake atk -c fetchall
bitbake enchant -c fetchall
bitbake liburcu -c fetchall
bitbake nss-myhostname -c fetchall
bitbake libiconv -c fetchall
bitbake libiconv -c fetchall
bitbake libsoup-2.4 -c fetchall
bitbake libffi -c fetchall
bitbake pinentry -c fetchall
bitbake libfm-extra -c fetchall
bitbake libfm -c fetchall
bitbake l -c fetchallsd -c fetchall
bitbake libnl -c fetchall
bitbake puzzles -c fetchall
bitbake webkitgtk -c fetchall
bitbake matchbox-terminal -c fetchall
bitbake pulseaudio-client-conf-sato -c fetchall
bitbake rxvt-unicode -c fetchall
bitbake rxvt-unicode -c fetchall
bitbake shutdown-desktop -c fetchall
bitbake sato-screenshot -c fetchall
bitbake matchbox-desktop -c fetchall
bitbake matchbox-session-sato -c fetchall
bitbake matchbox-panel-2 -c fetchall
bitbake matchbox-theme-sato -c fetchall
bitbake settings-daemon -c fetchall
bitbake pcmanfm -c fetchall
bitbake l3afpad -c fetchall
bitbake core-image-sato -c fetchall
bitbake core-image-sato-sdk-ptest -c fetchall
bitbake core-image-sato-sdk -c fetchall
bitbake core-image-sato-dev -c fetchall
bitbake matchbox-config-gtk -c fetchall
bitbake matchbox-keyboard -c fetchall
bitbake packagegroup-core-x11-sato -c fetchall
bitbake xf86-video-intel -c fetchall
bitbake xf86-video-omap -c fetchall
bitbake xf86-video-vesa -c fetchall
bitbake xf86-input-keyboard -c fetchall
bitbake xf86-input-libinput -c fetchall
bitbake xf86-input-evdev -c fetchall
bitbake xf86-input-keyboard -c fetchall
bitbake xf86-video-fbdev -c fetchall
bitbake xf86-input-synaptics -c fetchall
bitbake xf86-video-omapfb -c fetchall
bitbake xf86-video-vmware -c fetchall
bitbake xf86-input-mouse -c fetchall
bitbake xf86-input-mouse -c fetchall
bitbake xf86-input-synaptics -c fetchall
bitbake xf86-input-vmmouse -c fetchall
bitbake xf86-video-cirrus -c fetchall
bitbake clutter-gtk-1.0 -c fetchall
bitbake clutter-gst-3.0 -c fetchall
bitbake clutter-1.0 -c fetchall
bitbake libdrm -c fetchall
bitbake libmatchbox -c fetchall
bitbake encodings -c fetchall
bitbake font-alias -c fetchall
bitbake font-util -c fetchall
bitbake xorg-minimal-fonts -c fetchall
bitbake cantarell-fonts -c fetchall
bitbake fstests -c fetchall
bitbake menu-cache -c fetchall
bitbake xvideo-tests -c fetchall
bitbake xcursor-transparent-theme -c fetchall
bitbake libepoxy -c fetchall
bitbake mini-x-session -c fetchall
bitbake libfakekey -c fetchall
bitbake weston-init -c fetchall
bitbake wayland -c fetchall
bitbake libinput -c fetchall
bitbake weston -c fetchall
bitbake wayland-protocols -c fetchall
bitbake mtdev -c fetchall
bitbake waffle -c fetchall
bitbake piglit -c fetchall
bitbake xserver-xf86-config -c fetchall
bitbake xserver-xorg -c fetchall
bitbake libxcomposite -c fetchall
bitbake libxt -c fetchall
bitbake libxrandr -c fetchall
bitbake libxvmc -c fetchall
bitbake libxxf86dga -c fetchall
bitbake libxdamage -c fetchall
bitbake libxscrnsaver -c fetchall
bitbake libxxf86misc -c fetchall
bitbake libxkbcommon -c fetchall
bitbake libxi -c fetchall
bitbake libxkbfile -c fetchall
bitbake libxshmfence -c fetchall
bitbake libx11 -c fetchall
bitbake libxcalibrate -c fetchall
bitbake libxtst -c fetchall
bitbake libxcb -c fetchall
bitbake libxv -c fetchall
bitbake libxmu -c fetchall
bitbake libxfixes -c fetchall
bitbake xcb-util -c fetchall
bitbake xtrans -c fetchall
bitbake libxext -c fetchall
bitbake libxpm -c fetchall
bitbake libxau -c fetchall
bitbake libxinerama -c fetchall
bitbake libxcursor -c fetchall
bitbake libxfont -c fetchall
bitbake libxxf86vm -c fetchall
bitbake libice -c fetchall
bitbake libxres -c fetchall
bitbake libsm -c fetchall
bitbake xcb-util-keysyms -c fetchall
bitbake libxdmcp -c fetchall
bitbake pixman -c fetchall
bitbake xcb-util-image -c fetchall
bitbake libx11-diet -c fetchall
bitbake libdmx -c fetchall
bitbake libfontenc -c fetchall
bitbake xcb-util-wm -c fetchall
bitbake xcb-util-renderutil -c fetchall
bitbake libpciaccess -c fetchall
bitbake xkeyboard-config -c fetchall
bitbake libxrender -c fetchall
bitbake libpthread-stubs -c fetchall
bitbake libxft -c fetchall
bitbake xrestop -c fetchall
bitbake xserver-nodm-init -c fetchall
bitbake x11-common -c fetchall
bitbake startup-notification -c fetchall
bitbake pango -c fetchall
bitbake eglinfo-x11 -c fetchall
bitbake eglinfo-fb -c fetchall
bitbake matchbox-wm -c fetchall
bitbake xinput-calibrator -c fetchall
bitbake pointercal-xinput -c fetchall
bitbake mx-1.0 -c fetchall
bitbake cogl-1.0 -c fetchall
bitbake builder -c fetchall
bitbake freetype -c fetchall
bitbake libglu -c fetchall
bitbake mesa-demos -c fetchall
bitbake mesa-gl -c fetchall
bitbake mesa -c fetchall
bitbake mesa -c fetchall
bitbake cairo -c fetchall
bitbake libsdl -c fetchall
bitbake libsdl2 -c fetchall
bitbake harfbuzz -c fetchall
bitbake matchbox-session -c fetchall
bitbake core-image-x11 -c fetchall
bitbake core-image-clutter -c fetchall
bitbake core-image-weston -c fetchall
bitbake glew -c fetchall
bitbake libjpeg-turbo -c fetchall
bitbake packagegroup-core-x11 -c fetchall
bitbake packagegroup-core-x11-xserver -c fetchall
bitbake packagegroup-core-clutter -c fetchall
bitbake packagegroup-core-x11-base -c fetchall
bitbake xrandr -c fetchall
bitbake xeyes -c fetchall
bitbake rgb -c fetchall
bitbake xkbcomp -c fetchall
bitbake xmodmap -c fetchall
bitbake xvinfo -c fetchall
bitbake xdpyinfo -c fetchall
bitbake mkfontscale -c fetchall
bitbake xinit -c fetchall
bitbake xwininfo -c fetchall
bitbake x11perf -c fetchall
bitbake mkfontdir -c fetchall
bitbake xinput -c fetchall
bitbake xset -c fetchall
bitbake xev -c fetchall
bitbake xprop -c fetchall
bitbake xhost -c fetchall
bitbake xauth -c fetchall
bitbake fontconfig -c fetchall
bitbake makedepend -c fetchall
bitbake util-macros -c fetchall
bitbake gccmakedep -c fetchall
bitbake pong-clock -c fetchall
bitbake ttf-bitstream-vera -c fetchall
bitbake liberation-fonts -c fetchall
bitbake dmxproto -c fetchall
bitbake inputproto -c fetchall
bitbake presentproto -c fetchall
bitbake compositeproto -c fetchall
bitbake kbproto -c fetchall
bitbake xextproto -c fetchall
bitbake xf86miscproto -c fetchall
bitbake xineramaproto -c fetchall
bitbake calibrateproto -c fetchall
bitbake dri2proto -c fetchall
bitbake videoproto -c fetchall
bitbake xcmiscproto -c fetchall
bitbake dri3proto -c fetchall
bitbake recordproto -c fetchall
bitbake xf86dgaproto -c fetchall
bitbake scrnsaverproto -c fetchall
bitbake bigreqsproto -c fetchall
bitbake fixesproto -c fetchall
bitbake glproto -c fetchall
bitbake xf86vidmodeproto -c fetchall
bitbake damageproto -c fetchall
bitbake xcb-proto -c fetchall
bitbake randrproto -c fetchall
bitbake renderproto -c fetchall
bitbake xproto -c fetchall
bitbake resourceproto -c fetchall
bitbake xf86driproto -c fetchall
bitbake fontsproto -c fetchall
bitbake libxml2 -c fetchall
bitbake ncurses+20160625 -c fetchall
bitbake glib-2.0 -c fetchall
bitbake bsd-headers -c fetchall
bitbake console-tools -c fetchall
bitbake psplash -c fetchall
bitbake sysvinit-inittabdsf -c fetchall
bitbake sysvinitdsf -c fetchall
bitbake coreutils -c fetchall
bitbake coreutils -c fetchall
bitbake testexport-tarball -c fetchall
bitbake package-index -c fetchall
bitbake meta-world-pkgdata -c fetchall
bitbake nativesdk-buildtools-perl-dummy -c fetchall
bitbake meta-environment-extsdk -c fetchall
bitbake buildtools-tarball -c fetchall
bitbake meta-toolchain -c fetchall
bitbake signing-keys -c fetchall
bitbake meta-ide-support -c fetchall
bitbake uninative-tarball -c fetchall
bitbake meta-extsdk-toolchain -c fetchall
bitbake meta-environment -c fetchall
bitbake initscripts -c fetchall
bitbake musl -c fetchall
bitbake os-release -c fetchall
bitbake kbd -c fetchall
bitbake zlib -c fetchall
bitbake glibc-initial -c fetchall
bitbake cross-localedef-native -c fetchall
bitbake glibc-mtrace -c fetchall
bitbake ldconfig-native -c fetchall
bitbake glibc-locale -c fetchall
bitbake glibc-scripts -c fetchall
bitbake glibc -c fetchall
bitbake netbase -c fetchall
bitbake fts -c fetchall
bitbake dbus-wait -c fetchall
bitbake initramfs-live-install-efi-testfs -c fetchall
bitbake initramfs-live-install -c fetchall
bitbake initramfs-live-boot -c fetchall
bitbake initramfs-framework -c fetchall
bitbake initramfs-boot -c fetchall
bitbake initramfs-live-install-efi -c fetchall
bitbake initramfs-live-install-testfs -c fetchall
bitbake readline -c fetchall
bitbake readline -c fetchall
bitbake libcgroup -c fetchall
bitbake dropbear -c fetchall
bitbake volatile-binds -c fetchall
bitbake eudev -c fetchall
bitbake udev-extraconf -c fetchall
bitbake dbus-test -c fetchall
bitbake dbus-glib -c fetchall
bitbake dbus -c fetchall
bitbake glib-networking -c fetchall
bitbake base-passwd -c fetchall
bitbake util-linux -c fetchall
bitbake ifupdown -c fetchall
bitbake core-image-minimal-initramfs -c fetchall
bitbake core-image-minimal-dev -c fetchall
bitbake build-appliance-image -c fetchall
bitbake core-image-minimal -c fetchall
bitbake core-image-base -c fetchall
bitbake core-image-minimal-mtdutils -c fetchall
bitbake expat -c fetchall
bitbake packagegroup-core-eclipse-debug -c fetchall
bitbake packagegroup-self-hosted -c fetchall
bitbake packagegroup-core-sdk -c fetchall
bitbake packagegroup-core-ssh-dropbear -c fetchall
bitbake nativesdk-packagegroup-sdk-host -c fetchall
bitbake packagegroup-core-tools-profile -c fetchall
bitbake packagegroup-core-tools-testapps -c fetchall
bitbake packagegroup-core-boot -c fetchall
bitbake packagegroup-base -c fetchall
bitbake packagegroup-core-tools-debug -c fetchall
bitbake packagegroup-core-nfs -c fetchall
bitbake packagegroup-core-ssh-openssh -c fetchall
bitbake packagegroup-core-standalone-sdk-target -c fetchall
bitbake packagegroup-core-buildessential -c fetchall
bitbake packagegroup-cross-canadian -c fetchall
bitbake gettext-minimal-native -c fetchall
bitbake gettext -c fetchall
bitbake gettext -c fetchall
bitbake update-rc.d -c fetchall
bitbake base-files -c fetchall
bitbake systemd-systemctl-native -c fetchall
bitbake systemd -c fetchall
bitbake systemd-serialgetty -c fetchall
bitbake systemd-compat-units -c fetchall
bitbake busybox -c fetchall
bitbake busybox -c fetchall
bitbake init-ifupdown -c fetchall
bitbake sysfsutils -c fetchall
bitbake gzip -c fetchall
bitbake gzip -c fetchall
bitbake blktool-7 -c fetchall
bitbake libpam -c fetchall
bitbake texi2html -c fetchall
bitbake slang -c fetchall
bitbake msmtp -c fetchall
bitbake ghostscript -c fetchall
bitbake libtirpc -c fetchall
bitbake bzip2 -c fetchall
bitbake xdg-utils -c fetchall
bitbake procps -c fetchall
bitbake groff -c fetchall
bitbake groff -c fetchall
bitbake tar -c fetchall
bitbake tar -c fetchall
bitbake at -c fetchall
bitbake sudop1 -c fetchall
bitbake iptables -c fetchall
bitbake watchdog-config -c fetchall
bitbake watchdog -c fetchall
bitbake libnewt -c fetchall
bitbake libnewt-python -c fetchall
bitbake net-tools-26 -c fetchall
bitbake hdparm -c fetchall
bitbake mang -c fetchall
bitbake pbzip2 -c fetchall
bitbake screen -c fetchall
bitbake ed -c fetchall
bitbake ed -c fetchall
bitbake time -c fetchall
bitbake texinfo-dummy-native -c fetchall
bitbake findutils -c fetchall
bitbake findutils -c fetchall
bitbake lsof -c fetchall
bitbake logrotate -c fetchall
bitbake grepa -c fetchall
bitbake grep -c fetchall
bitbake sysstat -c fetchall
bitbake tzcode-nativea -c fetchall
bitbake stat -c fetchall
bitbake cracklib -c fetchall
bitbake stress -c fetchall
bitbake rpcbind -c fetchall
bitbake pigz -c fetchall
bitbake mingetty -c fetchall
bitbake zip -c fetchall
bitbake mktemp -c fetchall
bitbake libsolv -c fetchall
bitbake byacc -c fetchall
bitbake ltp -c fetchall
bitbake which -c fetchall
bitbake which -c fetchall
bitbake texinfo -c fetchall
bitbake texinfo -c fetchall
bitbake tcp-wrappers -c fetchall
bitbake mdadm -c fetchall
bitbake libuser -c fetchall
bitbake tzdataa -c fetchall
bitbake mc -c fetchall
bitbake mc -c fetchall
bitbake diffutils -c fetchall
bitbake diffutils -c fetchall
bitbake psmisc -c fetchall
bitbake gperf -c fetchall
bitbake gperf -c fetchall
bitbake bc -c fetchall
bitbake ethtool -c fetchall
bitbake unzip -c fetchall
bitbake chkconfig -c fetchall
bitbake chkconfig-alternatives-native -c fetchall
bitbake pax -c fetchall
bitbake sysklogd -c fetchall
bitbake bash -c fetchall
bitbake bash -c fetchall
bitbake cups -c fetchall
bitbake mailx-5 -c fetchall
bitbake cpio -c fetchall
bitbake cpio -c fetchall
bitbake lighttpd -c fetchall
bitbake libxml-sax-base-perl -c fetchall
bitbake libtimedate-perl -c fetchall
bitbake libxml-namespacesupport-perl -c fetchall
bitbake libxml-sax-perl -c fetchall
bitbake libconvert-asn1-perl -c fetchall
bitbake shadow-sysroot -c fetchall
bitbake shadow -c fetchall
bitbake shadow-securetty -c fetchall
bitbake libidn -c fetchall
bitbake libidn -c fetchall
bitbake sed -c fetchall
bitbake sed -c fetchall
bitbake iputils -c fetchall
bitbake asciidoc -c fetchall
bitbake lsb -c fetchall
bitbake lsbtest -c fetchall
bitbake lsbinitscripts -c fetchall
bitbake quota -c fetchall
bitbake pixz -c fetchall
bitbake libarchive -c fetchall
bitbake libaio -c fetchall
bitbake core-image-lsb -c fetchall
bitbake core-image-lsb-sdk -c fetchall
bitbake core-image-testmaster -c fetchall
bitbake core-image-full-cmdline -c fetchall
bitbake core-image-kernel-dev -c fetchall
bitbake core-image-lsb-dev -c fetchall
bitbake core-image-testmaster-initramfs -c fetchall
bitbake cwautomacros -c fetchall
bitbake gawk -c fetchall
bitbake gawk -c fetchall
bitbake foomatic-filters -c fetchall
bitbake packagegroup-core-full-cmdline -c fetchall
bitbake packagegroup-core-lsb -c fetchall
bitbake xinetd -c fetchall
bitbake man-pages -c fetchall
bitbake less -c fetchall
bitbake minicom -c fetchall
bitbake parted -c fetchall
bitbake cronie -c fetchall
bitbake wget -c fetchall
bitbake xz -c fetchall
bitbake libenv-perl -c fetchall
bitbake libfile-checktree-perl -c fetchall
bitbake libdumpvalue-perl -c fetchall
bitbake libclass-isa-perl -c fetchall
bitbake libi18n-collate-perl -c fetchall
bitbake libpod-plainer-perl -c fetchall
bitbake libpng12 -c fetchall
bitbake rt-tests -c fetchall
bitbake hwlatdetect -c fetchall
bitbake core-image-rt -c fetchall
bitbake core-image-rt-sdk -c fetchall
bitbake avahi -c fetchall
bitbake avahi-ui -c fetchall
bitbake bluez5 -c fetchall
bitbake wireless-tools.pre9 -c fetchall
bitbake bind-P3 -c fetchall
bitbake libnss-mdns -c fetchall
bitbake opensshp1 -c fetchall
bitbake portmap -c fetchall
bitbake ofono -c fetchall
bitbake ofono -c fetchall
bitbake mobile-broadband-provider-info -c fetchall
bitbake resolvconf -c fetchall
bitbake irda-utils -c fetchall
bitbake dhcp -c fetchall
bitbake ppp-dialin -c fetchall
bitbake libpcap -c fetchall
bitbake iproute2 -c fetchall
bitbake wpa-supplicant -c fetchall
bitbake iw -c fetchall
bitbake connman -c fetchall
bitbake connman-gnome -c fetchall
bitbake connman-conf -c fetchall
bitbake libnfsidmap -c fetchall
bitbake nfs-utils -c fetchall
bitbake opensslj -c fetchall
bitbake ppp -c fetchall
bitbake neard -c fetchall
bitbake socat -c fetchall
bitbake keymaps -c fetchall
bitbake acpid -c fetchall
bitbake pciutils -c fetchall
bitbake usbutils -c fetchall
bitbake usbinit -c fetchall
bitbake eee-acpi-scripts -c fetchall
bitbake hostap-utils -c fetchall
bitbake hostap-conf -c fetchall
bitbake apmd-15 -c fetchall
bitbake v86d -c fetchall
bitbake formfactor -c fetchall
bitbake alsa-state -c fetchall
bitbake lrzsz -c fetchall
bitbake u-boot-mkimage -c fetchall
bitbake u-boot-fw-utils -c fetchall
bitbake u-boot -c fetchall
bitbake libacpi -c fetchall
bitbake grub -c fetchall
bitbake grub -c fetchall
bitbake grub-efi -c fetchall
bitbake grub -c fetchall
bitbake gummiboot -c fetchall
bitbake pcmciautils -c fetchall
bitbake systemd-boot -c fetchall
bitbake setserial -c fetchall
bitbake pm-utils -c fetchall
bitbake gnu-efi -c fetchall
bitbake oprofile -c fetchall
bitbake dtc -c fetchall
bitbake modutils-initscripts -c fetchall
bitbake kmod-native -c fetchall
bitbake kmod -c fetchall
bitbake depmodwrapper-cross -c fetchall
bitbake sysprof -c fetchall
bitbake linux-libc-headers -c fetchall
bitbake linux-libc-headers -c fetchall
bitbake latencytop -c fetchall
bitbake blktrace -c fetchall
bitbake kexec-tools -c fetchall
bitbake libpfm4 -c fetchall
bitbake kern-tools-native -c fetchall
bitbake powertop -c fetchall
bitbake lttng-ust -c fetchall
bitbake lttng-modules -c fetchall
bitbake babeltrace -c fetchall
bitbake lttng-tools -c fetchall
bitbake systemtap -c fetchall
bitbake systemtap-uprobes -c fetchall
bitbake linux-firmware -c fetchall
bitbake trace-cmd -c fetchall
bitbake kernelshark -c fetchall
bitbake cryptodev-linux -c fetchall
bitbake cryptodev-module -c fetchall
bitbake cryptodev-tests -c fetchall
bitbake perf -c fetchall
bitbake linux-yocto-dev -c fetchall
bitbake linux-yocto -c fetchall
bitbake linux-yocto -c fetchall
bitbake linux-yocto-tiny -c fetchall
bitbake linux-dummy -c fetchall
bitbake linux-yocto-rt -c fetchall
bitbake linux-yocto-rt -c fetchall
bitbake linux-yocto-tiny -c fetchall
bitbake kernel-devsrc -c fetchall
bitbake linux-yocto -c fetchall
bitbake linux-yocto-rt -c fetchall
bitbake linux-yocto-tiny -c fetchall
bitbake gdk-pixbuf -c fetchall
bitbake gtk-icon-utils-native -c fetchall
bitbake gtk+3 -c fetchall
bitbake gtk+ -c fetchall
bitbake json-glib -c fetchall
bitbake epiphany -c fetchall
bitbake libnotify -c fetchall
bitbake gcr -c fetchall
bitbake hicolor-icon-theme -c fetchall
bitbake libwnck3 -c fetchall
bitbake librsvg -c fetchall
bitbake gnome-desktop3 -c fetchall
bitbake adwaita-icon-theme -c fetchall
bitbake gconf -c fetchall
bitbake libart-lgpl -c fetchall
bitbake gnome-common -c fetchall
bitbake gnome-themes-standard -c fetchall
bitbake gobject-introspection -c fetchall
bitbake gtk-doc -c fetchall
bitbake libgudev -c fetchall
bitbake gsettings-desktop-schemas -c fetchall
bitbake libsecret -c fetchall
bitbake ffmpeg -c fetchall
bitbake tremor -c fetchall
bitbake lame -c fetchall
bitbake gstreamer1.0-rtsp-server -c fetchall
bitbake gstreamer1.0-omx -c fetchall
bitbake gstreamer1.0-plugins-base -c fetchall
bitbake gstreamer1.0-plugins-bad -c fetchall
bitbake gstreamer1.0-plugins-ugly -c fetchall
bitbake gstreamer1.0-libav -c fetchall
bitbake gstreamer1.0 -c fetchall
bitbake gstreamer1.0-plugins-good -c fetchall
bitbake gstreamer1.0-plugins-good -c fetchall
bitbake gstreamer1.0-plugins-base -c fetchall
bitbake gstreamer1.0-plugins-bad -c fetchall
bitbake gst-player -c fetchall
bitbake gstreamer1.0-omx -c fetchall
bitbake gstreamer1.0-plugins-ugly -c fetchall
bitbake gstreamer1.0-meta-base -c fetchall
bitbake gstreamer1.0-libav -c fetchall
bitbake gstreamer1.0 -c fetchall
bitbake tiff -c fetchall
bitbake liba52 -c fetchall
bitbake libid3tagb -c fetchall
bitbake flac -c fetchall
bitbake mpeg2dec -c fetchall
bitbake libsamplerate0 -c fetchall
bitbake libtheora -c fetchall
bitbake sbc -c fetchall
bitbake libsndfile1 -c fetchall
bitbake alsa-lib -c fetchall
bitbake alsa-tools -c fetchall
bitbake alsa-utils -c fetchall
bitbake alsa-utils-scripts -c fetchall
bitbake alsa-plugins -c fetchall
bitbake libomxil -c fetchall
bitbake speexdsprc3 -c fetchall
bitbake speexrc2 -c fetchall
bitbake x264 -c fetchall
bitbake mpg123 -c fetchall
bitbake libwebp -c fetchall
bitbake pulseaudio -c fetchall
bitbake libpng -c fetchall
bitbake libvorbis -c fetchall
bitbake libogg -c fetchall
bitbake m4-native -c fetchall
bitbake m4 -c fetchall
bitbake m4 -c fetchall
bitbake systemd-bootchart -c fetchall
bitbake openjade-native -c fetchall
bitbake unifdef -c fetchall
bitbake rpmresolve -c fetchall
bitbake rpm -c fetchall
bitbake help2man-native -c fetchall
bitbake docbook-sgml-dtd-3.1-native -c fetchall
bitbake docbook-sgml-dtd-4.5-native -c fetchall
bitbake docbook-sgml-dtd-4.1-native -c fetchall
bitbake syslinux -c fetchall
bitbake i2c-tools -c fetchall
bitbake linuxdoc-tools-native -c fetchall
bitbake gdb-cross-canadian -c fetchall
bitbake gdb-cross -c fetchall
bitbake gdb -c fetchall
bitbake nativesdk-qemu-helper -c fetchall
bitbake qemu-helper-native -c fetchall
bitbake qemu -c fetchall
bitbake qemuwrapper-cross -c fetchall
bitbake opkg-utils -c fetchall
bitbake gnu-config -c fetchall
bitbake gnu-config -c fetchall
bitbake automake -c fetchall
bitbake opensp -c fetchall
bitbake mklibs-native -c fetchall
bitbake zisofs-tools-native -c fetchall
bitbake ccache -c fetchall
bitbake dosfstools -c fetchall
bitbake dosfstools -c fetchall
bitbake docbook-dsssl-stylesheets-native -c fetchall
bitbake json-c -c fetchall
bitbake build-compare -c fetchall
bitbake xmlto -c fetchall
bitbake btrfs-tools -c fetchall
bitbake subversion -c fetchall
bitbake quilt-native -c fetchall
bitbake quilt -c fetchall
bitbake distcc -c fetchall
bitbake vala -c fetchall
bitbake tcl -c fetchall
bitbake autogen-native -c fetchall
bitbake nativesdk-postinst-intercept -c fetchall
bitbake unfs3.r497 -c fetchall
bitbake binutils -c fetchall
bitbake binutils-cross-canadian -c fetchall
bitbake binutils-cross -c fetchall
bitbake binutils-crosssdk -c fetchall
bitbake desktop-file-utils-native -c fetchall
bitbake libtool-cross -c fetchall
bitbake libtool-native -c fetchall
bitbake libtool -c fetchall
bitbake nativesdk-libtool -c fetchall
bitbake bison -c fetchall
bitbake bison -c fetchall
bitbake dpkg -c fetchall
bitbake remake+dbg-1.1 -c fetchall
bitbake strace -c fetchall
bitbake kconfig-frontends -c fetchall
bitbake diffstat -c fetchall
bitbake cmake -c fetchall
bitbake cmake-native -c fetchall
bitbake opkg-arch-config -c fetchall
bitbake opkg -c fetchall
bitbake opkg-keyrings -c fetchall
bitbake squashfs-tools -c fetchall
bitbake e2fsprogs -c fetchall
bitbake intltool -c fetchall
bitbake autoconf -c fetchall
bitbake patchelf -c fetchall
bitbake docbook-xml-dtd4 -c fetchall
bitbake docbook-xsl-stylesheets -c fetchall
bitbake ruby -c fetchall
bitbake python3-numpy -c fetchall
bitbake python-numpy -c fetchall
bitbake run-postinsts -c fetchall
bitbake patch -c fetchall
bitbake patch -c fetchall
bitbake distcc-config -c fetchall
bitbake nfs-export-root -c fetchall
bitbake guilt-native -c fetchall
bitbake chrpath -c fetchall
bitbake mtd-utils -c fetchall
bitbake swig -c fetchall
bitbake python-scons-native -c fetchall
bitbake python-pexpect -c fetchall
bitbake python-nose -c fetchall
bitbake python-ptyprocess -c fetchall
bitbake python3-pip -c fetchall
bitbake python3-nose -c fetchall
bitbake python3-six -c fetchall
bitbake python-setuptools -c fetchall
bitbake python-async -c fetchall
bitbake python3-pycairo -c fetchall
bitbake python3-docutils -c fetchall
bitbake python3-gitdb -c fetchall
bitbake python-scons -c fetchall
bitbake python-git -c fetchall
bitbake python3-smmap -c fetchall
bitbake python-mako -c fetchall
bitbake python3-setuptools -c fetchall
bitbake python -c fetchall
bitbake python3-pygobject -c fetchall
bitbake python-gitdb -c fetchall
bitbake python-six -c fetchall
bitbake python3-async -c fetchall
bitbake python3-git -c fetchall
bitbake python3-native -c fetchall
bitbake python3-dbus -c fetchall
bitbake python3-mako -c fetchall
bitbake python-native -c fetchall
bitbake python-smartpm -c fetchall
bitbake python-pycurl -c fetchall
bitbake python-smmap -c fetchall
bitbake python3 -c fetchall
bitbake docbook-utils-native -c fetchall
bitbake sgml-common -c fetchall
bitbake sgml-common-native -c fetchall
bitbake yasm -c fetchall
bitbake apt -c fetchall
bitbake apt-native -c fetchall
bitbake ossp-uuid -c fetchall
bitbake elfutils -c fetchall
bitbake elfutils -c fetchall
bitbake cdrtools-native -c fetchall
bitbake make -c fetchall
bitbake make -c fetchall
bitbake pax-utils -c fetchall
bitbake perl-native -c fetchall
bitbake libxml-parser-perl -c fetchall
bitbake liburi-perl -c fetchall
bitbake libxml-perl -c fetchall
bitbake perl -c fetchall
bitbake liberror-perl -c fetchall
bitbake libxml-simple-perl -c fetchall
bitbake dmidecode -c fetchall
bitbake git -c fetchall
bitbake icon-naming-utils -c fetchall
bitbake orc -c fetchall
bitbake pkgconfig -c fetchall
bitbake rsync -c fetchall
bitbake rsync -c fetchall
bitbake bootchart2 -c fetchall
bitbake prelink -c fetchall
bitbake cve-check-tool -c fetchall
bitbake mtools -c fetchall
bitbake mtools -c fetchall
bitbake icecc-create-env-native -c fetchall
bitbake packagegroup-core-device-devel -c fetchall
bitbake valgrind -c fetchall
bitbake gptfdisk -c fetchall
bitbake nasm -c fetchall
bitbake mmc-utils -c fetchall
bitbake expect -c fetchall
bitbake guile -c fetchall
bitbake tcf-agent -c fetchall
bitbake mkelfimage -c fetchall
bitbake file -c fetchall
bitbake sgmlspl-native -c fetchall
bitbake libgcc-initial -c fetchall
bitbake gcc-cross-canadian -c fetchall
bitbake gcc-sanitizers -c fetchall
bitbake gcc-crosssdk -c fetchall
bitbake gcc -c fetchall
bitbake gcc-runtime -c fetchall
bitbake gcc-crosssdk -c fetchall
bitbake gcc-cross -c fetchall
bitbake libgfortran -c fetchall
bitbake gcc-cross-canadian -c fetchall
bitbake gcc-cross-initial -c fetchall
bitbake gcc-crosssdk-initial -c fetchall
bitbake gcc -c fetchall
bitbake gcc-cross -c fetchall
bitbake libgcc-initial -c fetchall
bitbake libgcc -c fetchall
bitbake gcc-source -c fetchall
bitbake gcc-cross-initial -c fetchall
bitbake gcc-crosssdk-initial -c fetchall
bitbake gcc-sanitizers -c fetchall
bitbake gcc-source -c fetchall
bitbake gcc-runtime -c fetchall
bitbake libgcc -c fetchall
bitbake libgfortran -c fetchall
bitbake pseudo -c fetchall
bitbake pseudo -c fetchall
bitbake flex -c fetchall
bitbake makedevs -c fetchall
bitbake core-image-multilib-example -c fetchall
bitbake service -c fetchall
bitbake useradd-example -c fetchall
bitbake hello-mod -c fetchall
bitbake linux-yocto-custom -c fetchall
bitbake tiny-init -c fetchall
bitbake libxpm -c fetchall
bitbake mtd-utils -c fetchall
bitbake hello -c fetchall
bitbake hello -c fetchall
bitbake gma500-gfx-check -c fetchall
bitbake libconnman-qt5 -c fetchall
bitbake libqofono -c fetchall
bitbake cinematicexperience -c fetchall
bitbake qt5-opengles2-test -c fetchall
bitbake qt5ledscreen -c fetchall
bitbake qt5everywheredemo -c fetchall
bitbake quitindicators -c fetchall
bitbake qt5nmapper -c fetchall
bitbake qt5nmapcarousedemo -c fetchall
bitbake qtsmarthome -c fetchall
bitbake quitbattery -c fetchall
bitbake qt3d -c fetchall
bitbake qtmultimedia -c fetchall
bitbake qtnetworkauth -c fetchall
bitbake qtdeclarative -c fetchall
bitbake qtwayland -c fetchall
bitbake qtbase -c fetchall
bitbake qttranslations -c fetchall
bitbake qtwebengine -c fetchall
bitbake qtenginio -c fetchall
bitbake qtquick1 -c fetchall
bitbake qttools -c fetchall
bitbake qtwebkit -c fetchall
bitbake qtscript -c fetchall
bitbake qtgraphicaleffects -c fetchall
bitbake qtconnectivity -c fetchall
bitbake qtcanvas3d -c fetchall
bitbake qtwebsockets -c fetchall
bitbake qtxmlpatterns -c fetchall
bitbake qtx11extras -c fetchall
bitbake qtsystems -c fetchall
bitbake qtcharts -c fetchall
bitbake qtsensors -c fetchall
bitbake qtimageformats -c fetchall
bitbake qtlocation -c fetchall
bitbake qtserialport -c fetchall
bitbake qtdatavis3d -c fetchall
bitbake qt5-creator -c fetchall
bitbake qtscxml -c fetchall
bitbake qtbase-native -c fetchall
bitbake qtserialbus -c fetchall
bitbake qtsvg -c fetchall
bitbake qtwebchannel -c fetchall
bitbake qtquickcontrols2 -c fetchall
bitbake qtquickcontrols -c fetchall
bitbake nativesdk-qtbase -c fetchall
bitbake qtvirtualkeyboard -c fetchall
bitbake qt5-plugin-generic-vboxtouch -c fetchall
bitbake qtwebkit-examples -c fetchall
bitbake qtgamepad -c fetchall
bitbake tufao -c fetchall
bitbake maliit-plugins-qt5 -c fetchall
bitbake maliit-framework-qt5 -c fetchall
bitbake meta-toolchain-qt5 -c fetchall
bitbake quazip -c fetchall
bitbake qtchooser -c fetchall
bitbake qsiv -c fetchall
bitbake packagegroup-qt5-toolchain-target -c fetchall
bitbake packagegroup-qt5-qtcreator-debug -c fetchall
bitbake nativesdk-packagegroup-qt5-toolchain-host -c fetchall
bitbake qt5-demo-extrafiles -c fetchall
bitbake net-persistent-mac -c fetchall
bitbake bcm4329-nvram-config -c fetchall
bitbake bcm4330-nvram-config -c fetchall
bitbake u-boot-script-boundary -c fetchall
bitbake u-boot-gateworks-imx -c fetchall
bitbake u-boot-script-gateworks-imx -c fetchall
bitbake u-boot-compulab -c fetchall
bitbake u-boot-congatec -c fetchall
bitbake u-boot-boundary -c fetchall
bitbake u-boot-toradex -c fetchall
bitbake u-boot-timesys -c fetchall
bitbake u-boot-variscite -c fetchall
bitbake u-boot-karo -c fetchall
bitbake mqxboot -c fetchall
bitbake mqxboot -c fetchall
bitbake libmcc2 -c fetchall
bitbake libmcc -c fetchall
bitbake kernel-module-mcc-toradex+toradex2 -c fetchall
bitbake kernel-module-mcc -c fetchall
bitbake linux-boundary-rt -c fetchall
bitbake linux-boundary -c fetchall
bitbake linux-wandboard -c fetchall
bitbake linux-warp7 -c fetchall
bitbake linux-compulab -c fetchall
bitbake linux-toradex -c fetchall
bitbake linux-advantech -c fetchall
bitbake linux-toradex -c fetchall
bitbake linux-cfa -c fetchall
bitbake linux-toradex -c fetchall
bitbake linux-congatec -c fetchall
bitbake linux-variscite -c fetchall
bitbake linux-toradex -c fetchall
bitbake linux-karo -c fetchall
bitbake linux-gateworks-imx -c fetchall
bitbake linux-wandboard-rt -c fetchall
bitbake linux-denx -c fetchall
bitbake linux-timesys -c fetchall
bitbake cef3 -c fetchall
bitbake chromium-wayland -c fetchall
bitbake chromium -c fetchall
bitbake firefox-addon-webconverger -c fetchall
bitbake mozilla-devscripts -c fetchall
bitbake firefoxesr -c fetchall
bitbake firefox-l10n-knesr -c fetchall
bitbake firefox-l10n-plesr -c fetchall
bitbake firefox-l10n-achesr -c fetchall
bitbake firefox-l10n-pt-bresr -c fetchall
bitbake firefox-l10n-faesr -c fetchall
bitbake firefox-l10n-itesr -c fetchall
bitbake firefox-l10n-viesr -c fetchall
bitbake firefox-l10n-gu-inesr -c fetchall
bitbake firefox-l10n-mkesr -c fetchall
bitbake firefox-l10n-bn-bdesr -c fetchall
bitbake firefox-l10n-afesr -c fetchall
bitbake firefox-l10n-taesr -c fetchall
bitbake firefox-l10n-huesr -c fetchall
bitbake firefox-l10n-hy-amesr -c fetchall
bitbake firefox-l10n-fresr -c fetchall
bitbake firefox-l10n-elesr -c fetchall
bitbake firefox-l10n-es-clesr -c fetchall
bitbake firefox-l10n-roesr -c fetchall
bitbake firefox-l10n-kmesr -c fetchall
bitbake firefox-l10n-es-aresr -c fetchall
bitbake firefox-l10n-sresr -c fetchall
bitbake firefox-l10n-es-esesr -c fetchall
bitbake firefox-l10n-teesr -c fetchall
bitbake firefox-l10n-sv-seesr -c fetchall
bitbake firefox-l10n-msesr -c fetchall
bitbake firefox-l10n-en-gbesr -c fetchall
bitbake firefox-l10n-bgesr -c fetchall
bitbake firefox-l10n-sqesr -c fetchall
bitbake firefox-l10n-csesr -c fetchall
bitbake firefox-l10n-daesr -c fetchall
bitbake firefox-l10n-pt-ptesr -c fetchall
bitbake firefox-l10n-nb-noesr -c fetchall
bitbake firefox-l10n-kkesr -c fetchall
bitbake firefox-l10n-siesr -c fetchall
bitbake firefox-l10n-ltesr -c fetchall
bitbake firefox-l10n-fy-nlesr -c fetchall
bitbake firefox-l10n-koesr -c fetchall
bitbake firefox-l10n-ga-ieesr -c fetchall
bitbake firefox-l10n-bsesr -c fetchall
bitbake firefox-l10n-bn-inesr -c fetchall
bitbake firefox-l10n-es-mxesr -c fetchall
bitbake firefox-l10n-nn-noesr -c fetchall
bitbake firefox-l10n-hresr -c fetchall
bitbake firefox-l10n-mlesr -c fetchall
bitbake firefox-l10n-lvesr -c fetchall
bitbake firefox-l10n-caesr -c fetchall
bitbake firefox-l10n-euesr -c fetchall
bitbake firefox-l10n-ruesr -c fetchall
bitbake firefox-l10n-sonesr -c fetchall
bitbake firefox-l10n-oresr -c fetchall
bitbake firefox-l10n-tresr -c fetchall
bitbake firefox-l10n-deesr -c fetchall
bitbake firefox-l10n-zh-twesr -c fetchall
bitbake firefox-l10n-fiesr -c fetchall
bitbake firefox-l10n-glesr -c fetchall
bitbake firefox-l10n-etesr -c fetchall
bitbake firefox-l10n-dsbesr -c fetchall
bitbake firefox-l10n-eoesr -c fetchall
bitbake firefox-l10n-slesr -c fetchall
bitbake firefox-l10n-maiesr -c fetchall
bitbake firefox-l10n-thesr -c fetchall
bitbake firefox-l10n-lijesr -c fetchall
bitbake firefox-l10n-xhesr -c fetchall
bitbake firefox-l10n-en-zaesr -c fetchall
bitbake firefox-l10n-gnesr -c fetchall
bitbake firefox-l10n-jaesr -c fetchall
bitbake firefox-l10n-nlesr -c fetchall
bitbake firefox-l10n-hsbesr -c fetchall
bitbake firefox-l10n-ffesr -c fetchall
bitbake firefox-l10n-skesr -c fetchall
bitbake firefox-l10n-astesr -c fetchall
bitbake firefox-l10n-rmesr -c fetchall
bitbake firefox-l10n-hi-inesr -c fetchall
bitbake firefox-l10n-heesr -c fetchall
bitbake firefox-l10n-ukesr -c fetchall
bitbake firefox-l10n-isesr -c fetchall
bitbake firefox-l10n-mresr -c fetchall
bitbake firefox-l10n-azesr -c fetchall
bitbake firefox-l10n-cyesr -c fetchall
bitbake firefox-l10n-bresr -c fetchall
bitbake firefox-l10n-pa-inesr -c fetchall
bitbake firefox-l10n-uzesr -c fetchall
bitbake firefox-l10n-anesr -c fetchall
bitbake firefox-l10n-asesr -c fetchall
bitbake firefox-l10n-en-usesr -c fetchall
bitbake firefox-l10n-aresr -c fetchall
bitbake firefox-l10n-idesr -c fetchall
bitbake firefox-l10n-beesr -c fetchall
bitbake firefox-l10n-gdesr -c fetchall
bitbake firefox-l10n-zh-cnesr -c fetchall
bitbake goffice -c fetchall
bitbake florence -c fetchall
bitbake tracker -c fetchall
bitbake gtk-theme-torturer -c fetchall
bitbake gparted -c fetchall
bitbake gnome-mplayer -c fetchall
bitbake gmtk -c fetchall
bitbake epdfview -c fetchall
bitbake pinpoint -c fetchall
bitbake cheese -c fetchall
bitbake obexd -c fetchall
bitbake network-manager-applet -c fetchall
bitbake gnumeric -c fetchall
bitbake gnome-bluetooth -c fetchall
bitbake gnome-mime-data -c fetchall
bitbake libxklavier -c fetchall
bitbake wv -c fetchall
bitbake gvfs -c fetchall
bitbake libgnome -c fetchall
bitbake libgnomeui -c fetchall
bitbake libgnomecanvas -c fetchall
bitbake libgnomekbd -c fetchall
bitbake devilspie2 -c fetchall
bitbake zenity -c fetchall
bitbake gnome-vfs -c fetchall
bitbake faenza-icon-theme -c fetchall
bitbake gnome-menus -c fetchall
bitbake gnome-menus3 -c fetchall
bitbake gnome-control-center -c fetchall
bitbake l -c fetchallonobo -c fetchall
bitbake l -c fetchallonoboui -c fetchall
bitbake gdm -c fetchall
bitbake desktop-file-utils -c fetchall
bitbake gthumb -c fetchall
bitbake gnome-backgrounds -c fetchall
bitbake dconf -c fetchall
bitbake gedit -c fetchall
bitbake libart-lgpl -c fetchall
bitbake gnome-panel3 -c fetchall
bitbake gnome-panel -c fetchall
bitbake evolution-data-server -c fetchall
bitbake libgdata -c fetchall
bitbake gnome-disk-utility -c fetchall
bitbake libwnck -c fetchall
bitbake system-tools-backends -c fetchall
bitbake gnome-themes -c fetchall
bitbake dates -c fetchall
bitbake contacts -c fetchall
bitbake tasks -c fetchall
bitbake tasks -c fetchall
bitbake contacts -c fetchall
bitbake gtksourceview2 -c fetchall
bitbake libgsf -c fetchall
bitbake gnome-settings-daemon -c fetchall
bitbake gnome-system-monitor -c fetchall
bitbake evince -c fetchall
bitbake gnome-keyring -c fetchall
bitbake libgnome-keyring -c fetchall
bitbake libidl -c fetchall
bitbake libidl-native -c fetchall
bitbake gnome-desktop -c fetchall
bitbake orbit2 -c fetchall
bitbake metacity -c fetchall
bitbake gnome-session -c fetchall
bitbake gnome-terminal -c fetchall
bitbake libgnomeprint -c fetchall
bitbake libgnomecups -c fetchall
bitbake abiword -c fetchall
bitbake libgtop -c fetchall
bitbake gnome-power-manager -c fetchall
bitbake libgweather3 -c fetchall
bitbake libgweather -c fetchall
bitbake gcalctool -c fetchall
bitbake gtk-engines -c fetchall
bitbake nautilus3 -c fetchall
bitbake nautilus -c fetchall
bitbake libgtkstylus -c fetchall
bitbake initramfs-debug -c fetchall
bitbake initramfs-debug-image -c fetchall
bitbake initramfs-kexecboot-image -c fetchall
bitbake initramfs-kexecboot-klibc-image -c fetchall
bitbake kexecboot-cfg -c fetchall
bitbake kexecboot -c fetchall
bitbake kexec-tools-klibc -c fetchall
bitbake linux-yocto-tiny-kexecboot -c fetchall
bitbake gr -c fetchally -c fetchall
bitbake ubi-utils-klibc -c fetchall
bitbake dracut -c fetchall
bitbake klcc-cross -c fetchall
bitbake klibc -c fetchall
bitbake klibc-utils -c fetchall
bitbake klibc-static-utils -c fetchall
bitbake fcgi -c fetchall
bitbake spawn-fcgi -c fetchall
bitbake nostromo -c fetchall
bitbake hiawatha -c fetchall
bitbake cherokee -c fetchall
bitbake apache-websocket -c fetchall
bitbake monkey -c fetchall
bitbake sthttpd -c fetchall
bitbake nginx -c fetchall
bitbake nginx -c fetchall
bitbake apache2 -c fetchall
bitbake apache2-native -c fetchall
bitbake xdebug -c fetchall
bitbake phpmyadmin -c fetchall
bitbake netdata -c fetchall
bitbake webmin -c fetchall
bitbake physfs -c fetchall
bitbake fuse -c fetchall
bitbake owfsp1 -c fetchall
bitbake ifuse -c fetchall
bitbake logfsprogs -c fetchall
bitbake ntfs-3g-ntfsprogs -c fetchall
bitbake smbnetfs -c fetchall
bitbake unionfs-fuse -c fetchall
bitbake simple-mtpfs -c fetchall
bitbake fuse-exfat -c fetchall
bitbake yaffs2-utils -c fetchall
bitbake sshfs-fuse -c fetchall
bitbake xorriso -c fetchall
bitbake xfsdump -c fetchall
bitbake aufs-util -c fetchall
bitbake f2fs-tools -c fetchall
bitbake dmapi -c fetchall
bitbake xfsprogs -c fetchall
bitbake exfat-utils -c fetchall
bitbake xfce4-vala -c fetchall
bitbake core-image-minimal-xfce -c fetchall
bitbake imsettings -c fetchall
bitbake xfce4-dev-tools -c fetchall
bitbake xfce4-power-manager -c fetchall
bitbake xfconf -c fetchall
bitbake xfce4-appfinder -c fetchall
bitbake xfdesktop -c fetchall
bitbake xfce4-settings -c fetchall
bitbake xfwm4 -c fetchall
bitbake thunar-volman -c fetchall
bitbake tumbler -c fetchall
bitbake gtk-xfce-engine -c fetchall
bitbake thunar -c fetchall
bitbake machine-host -c fetchall
bitbake xfce4-session -c fetchall
bitbake garcon -c fetchall
bitbake libxfce4util -c fetchall
bitbake xfce4-panel -c fetchall
bitbake libxfce4ui -c fetchall
bitbake packagegroup-xfce-base -c fetchall
bitbake packagegroup-xfce-extended -c fetchall
bitbake exo -c fetchall
bitbake xfce-polkit -c fetchall
bitbake ristretto -c fetchall
bitbake xfce4-mixer -c fetchall
bitbake orage -c fetchall
bitbake mousepad -c fetchall
bitbake gigolo -c fetchall
bitbake xfce4-notifyd -c fetchall
bitbake xfce4-terminal -c fetchall
bitbake xarchiver -c fetchall
bitbake xfce4-screenshooter -c fetchall
bitbake xfce4-taskmanager -c fetchall
bitbake openzone -c fetchall
bitbake xfwm4-themes -c fetchall
bitbake xfce-dusk-gtk3 -c fetchall
bitbake rodent-icon-theme -c fetchall
bitbake xfce4-notes-plugin -c fetchall
bitbake xfce4-smartbookmark-plugin -c fetchall
bitbake xfce4-battery-plugin -c fetchall
bitbake xfce4-fsguard-plugin -c fetchall
bitbake xfce4-wavelan-plugin -c fetchall
bitbake xfce4-systemload-plugin -c fetchall
bitbake xfce4-verve-plugin -c fetchall
bitbake xfce4-eyes-plugin -c fetchall
bitbake xfce4-sensors-plugin -c fetchall
bitbake xfce4-embed-plugin -c fetchall
bitbake xfce4-kbdleds-plugin -c fetchall
bitbake xfce4-closebutton-plugin -c fetchall
bitbake xfce4-mount-plugin -c fetchall
bitbake xfce4-places-plugin -c fetchall
bitbake xfce4-cpufreq-plugin -c fetchall
bitbake xfce4-equake-plugin -c fetchall
bitbake xfce4-pulseaudio-plugin -c fetchall
bitbake xfce4-netload-plugin -c fetchall
bitbake xfce4-hotcorner-plugin -c fetchall
bitbake xfce4-datetime-plugin -c fetchall
bitbake xfce4-whiskermenu-plugin -c fetchall
bitbake xfce4-time-out-plugin -c fetchall
bitbake xfce4-xkb-plugin -c fetchall
bitbake xfce4-timer-plugin -c fetchall
bitbake xfce4-genmon-plugin -c fetchall
bitbake xfce4-clipman-plugin -c fetchall
bitbake xfce4-diskperf-plugin -c fetchall
bitbake xfce4-weather-plugin -c fetchall
bitbake xfce4-cpugraph-plugin -c fetchall
bitbake xfce4-calculator-plugin -c fetchall
bitbake xfce4-mailwatch-plugin -c fetchall
bitbake thunar-media-tags-plugin -c fetchall
bitbake thunar-archive-plugin -c fetchall
bitbake xfce4-mpc-plugin -c fetchall
bitbake xfmpc -c fetchall
bitbake parole -c fetchall
bitbake packagegroup-xfce-multimedia -c fetchall
bitbake tunctl -c fetchall
bitbake ifenslave -c fetchall
bitbake wireshark -c fetchall
bitbake bridge-utils -c fetchall
bitbake libtalloc -c fetchall
bitbake memcached -c fetchall
bitbake netcat -c fetchall
bitbake netcat-openbsd -c fetchall
bitbake nuttcp -c fetchall
bitbake smcroute -c fetchall
bitbake fping -c fetchall
bitbake ntimed -c fetchall
bitbake lksctp-tools -c fetchall
bitbake libldb -c fetchall
bitbake traceroute -c fetchall
bitbake strongswan -c fetchall
bitbake drbd-utils -c fetchall
bitbake libtevent -c fetchall
bitbake ipsec-tools -c fetchall
bitbake nbd -c fetchall
bitbake c-ares -c fetchall
bitbake ipvsadm -c fetchall
bitbake chrony -c fetchall
bitbake iftoppre4 -c fetchall
bitbake arptables-4 -c fetchall
bitbake linux-atm -c fetchall
bitbake tcpdump -c fetchall
bitbake tcpslicea3 -c fetchall
bitbake cifs-utils -c fetchall
bitbake openvpn -c fetchall
bitbake dovecot -c fetchall
bitbake libtdb -c fetchall
bitbake netcf -c fetchall
bitbake geoip-perl -c fetchall
bitbake geoip -c fetchall
bitbake geoipupdate -c fetchall
bitbake pimd -c fetchall
bitbake phytool -c fetchall
bitbake ndisc6 -c fetchall
bitbake dnssec-conf -c fetchall
bitbake ssmping -c fetchall
bitbake tnftp -c fetchall
bitbake libesmtp -c fetchall
bitbake ypbind-mt -c fetchall
bitbake yp-tools -c fetchall
bitbake ypbind-mt -c fetchall
bitbake yp-tools -c fetchall
bitbake ntpp9 -c fetchall
bitbake fetchmail -c fetchall
bitbake cim-schema-docs -c fetchall
bitbake cim-schema-final -c fetchall
bitbake cim-schema-exper -c fetchall
bitbake mtr -c fetchall
bitbake lowpan-tools -c fetchall
bitbake curlpp -c fetchall
bitbake dnsmasq -c fetchall
bitbake ctdb -c fetchall
bitbake netperf -c fetchall
bitbake libmemcached -c fetchall
bitbake libmemcached -c fetchall
bitbake stunnel -c fetchall
bitbake esmtp -c fetchall
bitbake macchanger -c fetchall
bitbake aoetools -c fetchall
bitbake tcpreplay -c fetchall
bitbake netkit-tftp -c fetchall
bitbake netkit-rpc -c fetchall
bitbake netkit-ftp -c fetchall
bitbake netkit-rwho -c fetchall
bitbake netkit-rsh -c fetchall
bitbake netkit-rusers -c fetchall
bitbake netkit-telnet -c fetchall
bitbake iscsitarget+svn502 -c fetchall
bitbake nfacct -c fetchall
bitbake libmnl -c fetchall
bitbake libnftnl -c fetchall
bitbake conntrack-tools -c fetchall
bitbake ebtables-4 -c fetchall
bitbake libnetfilter-log -c fetchall
bitbake libnetfilter-cttimeout -c fetchall
bitbake libnetfilter-acct -c fetchall
bitbake libnetfilter-conntrack -c fetchall
bitbake libnetfilter-queue -c fetchall
bitbake libnetfilter-cthelper -c fetchall
bitbake nftables -c fetchall
bitbake libnfnetlink -c fetchall
bitbake ptpd -c fetchall
bitbake cyrus-sasl -c fetchall
bitbake tftp-hpa -c fetchall
bitbake postfix -c fetchall
bitbake atftp -c fetchall
bitbake autofs -c fetchall
bitbake lldpd -c fetchall
bitbake vsftpd -c fetchall
bitbake opensaf -c fetchall
bitbake ncftp -c fetchall
bitbake squid -c fetchall
bitbake vblade -c fetchall
bitbake dnrd -c fetchall
bitbake proftpdb -c fetchall
bitbake pure-ftpd -c fetchall
bitbake radvd -c fetchall
bitbake iscsi-initiator-utils-873 -c fetchall
bitbake xl2tpd -c fetchall
bitbake xl2tpd -c fetchall
bitbake accel-ppp -c fetchall
bitbake net-snmp -c fetchall
bitbake quagga -c fetchall
bitbake openl2tp -c fetchall
bitbake pptp-linux -c fetchall
bitbake radiusclient-ng -c fetchall
bitbake tsocksbeta5 -c fetchall
bitbake rp-pppoe -c fetchall
bitbake openflow -c fetchall
bitbake openflow -c fetchall
bitbake zeroconf -c fetchall
bitbake libdnet -c fetchall
bitbake wolfssl -c fetchall
bitbake relayd -c fetchall
bitbake snort -c fetchall
bitbake inetutils -c fetchall
bitbake crda -c fetchall
bitbake lftp -c fetchall
bitbake samba -c fetchall
bitbake daq -c fetchall
bitbake openconnect -c fetchall
bitbake ufw -c fetchall
bitbake vpnc -c fetchall
bitbake dhcpcd -c fetchall
bitbake sethdlc -c fetchall
bitbake vlan -c fetchall
bitbake mbedtls -c fetchall
bitbake wireless-regdb -c fetchall
bitbake netmap-modules -c fetchall
bitbake netmap -c fetchall
bitbake znc -c fetchall
bitbake python-pyparted -c fetchall
bitbake python-pyephem -c fetchall
bitbake python-pyro4 -c fetchall
bitbake python-thrift -c fetchall
bitbake gateone -c fetchall
bitbake python-txws -c fetchall
bitbake python3-werkzeug -c fetchall
bitbake python-strict-rfc3339 -c fetchall
bitbake python3-passlib -c fetchall
bitbake python-pyzmq -c fetchall
bitbake python3-lxml -c fetchall
bitbake python-pyserial -c fetchall
bitbake python-pyrex -c fetchall
bitbake python-prettytable -c fetchall
bitbake python-cryptography-vectors -c fetchall
bitbake python-parse-type -c fetchall
bitbake python-rfc3987 -c fetchall
bitbake python-dbusmock -c fetchall
bitbake python-daemonize -c fetchall
bitbake python-ujson -c fetchall
bitbake python-pyhamcrest -c fetchall
bitbake python-pyudev -c fetchall
bitbake python3-urllib3 -c fetchall
bitbake python-paho-mqtt -c fetchall
bitbake python-jsonpatch -c fetchall
bitbake python3-tornado -c fetchall
bitbake python-smbus -c fetchall
bitbake python3-pysocks -c fetchall
bitbake python-itsdangerous -c fetchall
bitbake python-feedformatter -c fetchall
bitbake python-pybind11 -c fetchall
bitbake python-pbr -c fetchall
bitbake python-backports-ssl -c fetchall
bitbake python3-flask-login -c fetchall
bitbake python-pycparser -c fetchall
bitbake python-idna -c fetchall
bitbake python3-pyasn1 -c fetchall
bitbake python3-six -c fetchall
bitbake python3-itsdangerous -c fetchall
bitbake python-visitor -c fetchall
bitbake python-backports-abc -c fetchall
bitbake python-iso8601 -c fetchall
bitbake python3-flask -c fetchall
bitbake python-tornado -c fetchall
bitbake python3-cryptography -c fetchall
bitbake python-lxml -c fetchall
bitbake python-flask-pymongo -c fetchall
bitbake python3-ndg-httpsclient -c fetchall
bitbake python-chardet -c fetchall
bitbake python-tornado-redis -c fetchall
bitbake python-zopeinterface -c fetchall
bitbake python-dateutil -c fetchall
bitbake python3-pycparser -c fetchall
bitbake python3-rfc3987 -c fetchall
bitbake python-markupsafe -c fetchall
bitbake python-pyparsing -c fetchall
bitbake python-evdev -c fetchall
bitbake python-cmd2 -c fetchall
bitbake python-flask-wtf -c fetchall
bitbake python3-strict-rfc3339 -c fetchall
bitbake python-jsonschema -c fetchall
bitbake python3-pretend -c fetchall
bitbake python3-requests -c fetchall
bitbake python-msgpack -c fetchall
bitbake python-vobject -c fetchall
bitbake python-imaging -c fetchall
bitbake python3-certifi -c fetchall
bitbake python-m2crypto -c fetchall
bitbake python-ldap -c fetchall
bitbake python-pam -c fetchall
bitbake python-flask-bootstrap -c fetchall
bitbake python-parse -c fetchall
bitbake python3-cython -c fetchall
bitbake python-gdata -c fetchall
bitbake python-feedparser -c fetchall
bitbake python3-jsonschema -c fetchall
bitbake python-cloudeebus -c fetchall
bitbake python-gevent -c fetchall
bitbake python-pyflakes -c fetchall
bitbake python-decorator -c fetchall
bitbake python-click -c fetchall
bitbake python-webdav -c fetchall
bitbake python-pygpgme -c fetchall
bitbake python-flask -c fetchall
bitbake python-xlrd -c fetchall
bitbake python3-webcolors -c fetchall
bitbake python3-iso8601 -c fetchall
bitbake python3-pymongo -c fetchall
bitbake python-pymisp -c fetchall
bitbake python-wtforms -c fetchall
bitbake python3-pyinotify -c fetchall
bitbake python-cffi -c fetchall
bitbake python-pip -c fetchall
bitbake python3-cryptography-vectors -c fetchall
bitbake python-sqlalchemy -c fetchall
bitbake python-pep8 -c fetchall
bitbake python-snakefood -c fetchall
bitbake python3-pymisp -c fetchall
bitbake python-netaddr -c fetchall
bitbake python3-markupsafe -c fetchall
bitbake python-bitarray -c fetchall
bitbake python-autobahn -c fetchall
bitbake python-ipaddress -c fetchall
bitbake python3-redis -c fetchall
bitbake python-setuptools-scm -c fetchall
bitbake python-prompt-toolkit -c fetchall
bitbake python3-pyopenssl -c fetchall
bitbake python-requests -c fetchall
bitbake python-pyopenssl -c fetchall
bitbake python-psutil -c fetchall
bitbake python-django -c fetchall
bitbake python-paste -c fetchall
bitbake python-pysocks -c fetchall
bitbake python-blinker -c fetchall
bitbake python-html5lib -c fetchall
bitbake python3-dateutil -c fetchall
bitbake python-enum34 -c fetchall
bitbake python-vcversioner -c fetchall
bitbake python3-pytest -c fetchall
bitbake python-greenlet -c fetchall
bitbake python-pyinotify -c fetchall
bitbake python3-vcversioner -c fetchall
bitbake python3-progress -c fetchall
bitbake python-progress -c fetchall
bitbake python-six -c fetchall
bitbake python-pyasn1 -c fetchall
bitbake python-jsonpointer -c fetchall
bitbake python-urllib3 -c fetchall
bitbake python-sparts -c fetchall
bitbake python-twisted -c fetchall
bitbake python-pyyaml -c fetchall
bitbake python3-pybind11 -c fetchall
bitbake python-ndg-httpsclient -c fetchall
bitbake python-dominate -c fetchall
bitbake python-functools32-2 -c fetchall
bitbake python-redis -c fetchall
bitbake python-slip-dbus -c fetchall
bitbake python3-decorator -c fetchall
bitbake python-cheetah -c fetchall
bitbake python-dbus -c fetchall
bitbake python-unidiff -c fetchall
bitbake python-singledispatch -c fetchall
bitbake python3-xlrd -c fetchall
bitbake python-numeric -c fetchall
bitbake python-certifi -c fetchall
bitbake python-jinja2 -c fetchall
bitbake python-cryptography -c fetchall
bitbake python-pyalsaaudio -c fetchall
bitbake python-whoosh -c fetchall
bitbake python3-wcwidth -c fetchall
bitbake python3-flask-pymongo -c fetchall
bitbake python3-whoosh -c fetchall
bitbake python-flask-navigation -c fetchall
bitbake python-mock -c fetchall
bitbake python3-click -c fetchall
bitbake python3-py -c fetchall
bitbake python-yappi -c fetchall
bitbake python-bcrypt -c fetchall
bitbake python-pretend -c fetchall
bitbake python-flask-bcrypt -c fetchall
bitbake python-flask-sqlalchemy -c fetchall
bitbake python-pylint -c fetchall
bitbake python-webcolors -c fetchall
bitbake python-pymongo -c fetchall
bitbake python-pyroute2 -c fetchall
bitbake python3-jinja2 -c fetchall
bitbake python-flask-login -c fetchall
bitbake python-behave -c fetchall
bitbake python-py -c fetchall
bitbake python3-prompt-toolkit -c fetchall
bitbake python3-feedformatter -c fetchall
bitbake python-matplotlib -c fetchall
bitbake python-pytz -c fetchall
bitbake python3-pyserial -c fetchall
bitbake python-mccabe -c fetchall
bitbake python-pytest-runner -c fetchall
bitbake python-cython -c fetchall
bitbake python-epydoc -c fetchall
bitbake python-django-south -c fetchall
bitbake python3-idna -c fetchall
bitbake python-ldap -c fetchall
bitbake python-pytest -c fetchall
bitbake python-monotonic -c fetchall
bitbake python-wcwidth -c fetchall
bitbake python-passlib -c fetchall
bitbake python3-cffi -c fetchall
bitbake python-pyrex-native -c fetchall
bitbake python-werkzeug -c fetchall
bitbake pyrtm -c fetchall
bitbake python-pyusbb2 -c fetchall
bitbake meta-toolchain-efl -c fetchall
bitbake webkit-efl -c fetchall
bitbake terminology -c fetchall
bitbake exquisite -c fetchall
bitbake e-wm-theme-b-and-w -c fetchall
bitbake elmdentica -c fetchall
bitbake forecasts -c fetchall
bitbake cpu -c fetchall
bitbake elbow -c fetchall
bitbake e-wm-theme-illume-efenniht -c fetchall
bitbake e-wm -c fetchall
bitbake rage -c fetchall
bitbake enjoy -c fetchall
bitbake exalt-client -c fetchall
bitbake ephoto -c fetchall
bitbake uptime -c fetchall
bitbake rain -c fetchall
bitbake e-wm -c fetchall
bitbake exquisite-theme-illume -c fetchall
bitbake screenshot -c fetchall
bitbake e-tasks -c fetchall
bitbake flame -c fetchall
bitbake elfe -c fetchall
bitbake diskio -c fetchall
bitbake emprint -c fetchall
bitbake e-wm -c fetchall
bitbake exalt -c fetchall
bitbake edje-viewer -c fetchall
bitbake illume-keyboards-shr -c fetchall
bitbake news -c fetchall
bitbake places -c fetchall
bitbake packagegroup-efl-sdk -c fetchall
bitbake packagegroup-x11-illume -c fetchall
bitbake packagegroup-efl-standalone-sdk-target -c fetchall
bitbake emotion-generic-players -c fetchall
bitbake edbus -c fetchall
bitbake azy -c fetchall
bitbake evas-generic-loaders -c fetchall
bitbake entrance -c fetchall
bitbake expedite -c fetchall
bitbake elementary-theme-efenniht -c fetchall
bitbake efl -c fetchall
bitbake epdf -c fetchall
bitbake elementary -c fetchall
bitbake libeweather -c fetchall
bitbake edb -c fetchall
bitbake expedite -c fetchall
bitbake engrave -c fetchall
bitbake e-wm-illume-dict-pl -c fetchall
bitbake libeflvala -c fetchall
bitbake imlib2 -c fetchall
bitbake mcnavi -c fetchall
bitbake lightmediascanner -c fetchall
bitbake python-efl -c fetchall
bitbake python-efl -c fetchall
bitbake python-edbus -c fetchall
bitbake bundler -c fetchall
bitbake fbreader -c fetchall
bitbake fbreader -c fetchall
bitbake libgpewidget -c fetchall
bitbake minilite -c fetchall
bitbake gpe-scap -c fetchall
bitbake mce-inject -c fetchall
bitbake mcelog -c fetchall
bitbake gflags -c fetchall
bitbake sjf2410-linux-native -c fetchall
bitbake s3c24xx-gpio -c fetchall
bitbake s3c64xx-gpio -c fetchall
bitbake lcms -c fetchall
bitbake espeak -c fetchall
bitbake espeak-data -c fetchall
bitbake tokyocabinet -c fetchall
bitbake enca -c fetchall
bitbake read-edid -c fetchall
bitbake tree -c fetchall
bitbake thin-provisioning-tools -c fetchall
bitbake libol -c fetchall
bitbake gpm -c fetchall
bitbake asio -c fetchall
bitbake pcsc-lite -c fetchall
bitbake htop -c fetchall
bitbake tomoyo-tools -c fetchall
bitbake cryptsetup -c fetchall
bitbake opencv -c fetchall
bitbake opencv -c fetchall
bitbake opencv-samples -c fetchall
bitbake smem -c fetchall
bitbake vboxguestdrivers -c fetchall
bitbake vboxguestdrivers -c fetchall
bitbake libatasmart -c fetchall
bitbake pngcheck -c fetchall
bitbake fltk -c fetchall
bitbake soci -c fetchall
bitbake numactl -c fetchall
bitbake libsmi -c fetchall
bitbake epeg -c fetchall
bitbake gd -c fetchall
bitbake openct -c fetchall
bitbake ckermit -c fetchall
bitbake libsdl2-ttf -c fetchall
bitbake libsdl-ttf -c fetchall
bitbake libssh -c fetchall
bitbake xchat -c fetchall
bitbake libraw1394 -c fetchall
bitbake mime-support -c fetchall
bitbake syslog-ng -c fetchall
bitbake portaudio-v19 -c fetchall
bitbake xmlstarlet -c fetchall
bitbake libinih -c fetchall
bitbake hidapi -c fetchall
bitbake iksemel -c fetchall
bitbake vala-terminal -c fetchall
bitbake gsoap -c fetchall
bitbake libee -c fetchall
bitbake xdg-user-dirs -c fetchall
bitbake eventlog -c fetchall
bitbake start-stop-daemon -c fetchall
bitbake libsodium -c fetchall
bitbake openldap -c fetchall
bitbake postgresql -c fetchall
bitbake system-config-keyboard -c fetchall
bitbake libtinyxml -c fetchall
bitbake procmail -c fetchall
bitbake synergy -c fetchall
bitbake unixodbc -c fetchall
bitbake mini-iconv -c fetchall
bitbake hwdata -c fetchall
bitbake flite-alsa -c fetchall
bitbake usbpath -c fetchall
bitbake sg3-utils -c fetchall
bitbake libssh2 -c fetchall
bitbake p910nd -c fetchall
bitbake libmicrohttpd -c fetchall
bitbake pps-tools -c fetchall
bitbake onig -c fetchall
bitbake lio-utils -c fetchall
bitbake liboauth -c fetchall
bitbake poco -c fetchall
bitbake upower -c fetchall
bitbake pam-passwdqc -c fetchall
bitbake zile -c fetchall
bitbake sdparm -c fetchall
bitbake libp11 -c fetchall
bitbake libmcrypt -c fetchall
bitbake edac-utils -c fetchall
bitbake lockdev -c fetchall
bitbake openmotif -c fetchall
bitbake opensc -c fetchall
bitbake mailcap -c fetchall
bitbake joe -c fetchall
bitbake nmong -c fetchall
bitbake libdbi -c fetchall
bitbake libdbi-drivers-1 -c fetchall
bitbake libeigen -c fetchall
bitbake pty-forward-native -c fetchall
bitbake serial-forward -c fetchall
bitbake log4c -c fetchall
bitbake xdelta3 -c fetchall
bitbake libtinyxml2 -c fetchall
bitbake wmiconfig -c fetchall
bitbake farsight2 -c fetchall
bitbake libnice -c fetchall
bitbake libetpan -c fetchall
bitbake imagemagick -c fetchall
bitbake liblinebreak -c fetchall
bitbake mariadb -c fetchall
bitbake mysql-python -c fetchall
bitbake mariadb-native -c fetchall
bitbake freerdp -c fetchall
bitbake minini.b -c fetchall
bitbake spitools -c fetchall
bitbake mongodb -c fetchall
bitbake usb-modeswitch-data -c fetchall
bitbake usb-modeswitch -c fetchall
bitbake evtest -c fetchall
bitbake daemontools -c fetchall
bitbake pv -c fetchall
bitbake gperftools -c fetchall
bitbake open-vcdiff -c fetchall
bitbake libusbg -c fetchall
bitbake digitemp -c fetchall
bitbake daemonize -c fetchall
bitbake nano -c fetchall
bitbake lzip -c fetchall
bitbake libnih -c fetchall
bitbake cpufrequtils -c fetchall
bitbake rsnapshot -c fetchall
bitbake benchfft -c fetchall
bitbake fftw -c fetchall
bitbake lmsensors -c fetchall
bitbake lmsensors-config -c fetchall
bitbake libutempter -c fetchall
bitbake gradm -c fetchall
bitbake ne10 -c fetchall
bitbake  -c fetchall -c fetchall
bitbake links-x11 -c fetchall
bitbake links -c fetchall
bitbake poppler-data -c fetchall
bitbake poppler -c fetchall
bitbake dstat -c fetchall
bitbake eject -c fetchall
bitbake hddtemp-beta15 -c fetchall
bitbake sqlite -c fetchall
bitbake dfu-util -c fetchall
bitbake dfu-util-native -c fetchall
bitbake lvm2 -c fetchall
bitbake re2c -c fetchall
bitbake udisks -c fetchall
bitbake udisks2 -c fetchall
bitbake log4cpp -c fetchall
bitbake fbset -c fetchall
bitbake fbset-modes -c fetchall
bitbake libgit2 -c fetchall
bitbake vim -c fetchall
bitbake vim-tiny -c fetchall
bitbake devmem2 -c fetchall
bitbake gnulib -c fetchall
bitbake libjs-jquery -c fetchall
bitbake libjs-sizzle -c fetchall
bitbake uthash -c fetchall
bitbake wbxml2 -c fetchall
bitbake libsyncml -c fetchall
bitbake libestr -c fetchall
bitbake ccid -c fetchall
bitbake hunspell -c fetchall
bitbake psqlodbc -c fetchall
bitbake mg -c fetchall
bitbake libcanberra -c fetchall
bitbake ctapi-common-14 -c fetchall
bitbake fb-test -c fetchall
bitbake geis -c fetchall
bitbake grail -c fetchall
bitbake frame -c fetchall
bitbake libftdi -c fetchall
bitbake libsoc -c fetchall
bitbake utouch-frame -c fetchall
bitbake utouch-evemu -c fetchall
bitbake utouch-mtview -c fetchall
bitbake multipath-tools -c fetchall
bitbake inotify-tools -c fetchall
bitbake gsl -c fetchall
bitbake ipmiutil -c fetchall
bitbake atop -c fetchall
bitbake rdfind -c fetchall
bitbake engine-pkcs11 -c fetchall
bitbake system-setup-keyboard -c fetchall
bitbake sharutils -c fetchall
bitbake pkcs11-helper -c fetchall
bitbake toscoterm -c fetchall
bitbake apcupsd -c fetchall
bitbake uim -c fetchall
bitbake openwbem -c fetchall
bitbake pidgin -c fetchall
bitbake libotr -c fetchall
bitbake pidgin-otr -c fetchall
bitbake emacs -c fetchall
bitbake lcov -c fetchall
bitbake augeas -c fetchall
bitbake picocom -c fetchall
bitbake anthyh -c fetchall
bitbake mbuffer -c fetchall
bitbake pxaregs -c fetchall
bitbake glog -c fetchall
bitbake ode -c fetchall
bitbake claws-plugin-rssyl -c fetchall
bitbake claws-plugin-mailmbox -c fetchall
bitbake claws-plugin-gtkhtml2-viewer -c fetchall
bitbake sylpheed -c fetchall
bitbake claws-mail -c fetchall
bitbake xf86-input-mtev -c fetchall
bitbake xf86-video-glamo -c fetchall
bitbake xf86-input-void -c fetchall
bitbake xf86-input-tslib -c fetchall
bitbake xf86-video-nouveau -c fetchall
bitbake xf86-video-ati -c fetchall
bitbake xf86-video-geode -c fetchall
bitbake clutter-box2d -c fetchall
bitbake jasper -c fetchall
bitbake xorg-fonts-100dpi -c fetchall
bitbake font-bitstream-100dpi -c fetchall
bitbake font-cursor-misc -c fetchall
bitbake font-adobe-100dpi -c fetchall
bitbake font-adobe-utopia-100dpi -c fetchall
bitbake font-bh-100dpi -c fetchall
bitbake font-bh-lucidatypewriter-100dpi -c fetchall
bitbake font-misc-misc -c fetchall
bitbake xserver-nodm-init -c fetchall
bitbake tslib -c fetchall
bitbake fim-rc1 -c fetchall
bitbake wayland-fits -c fetchall
bitbake slim -c fetchall
bitbake libvncserver -c fetchall
bitbake liblbxutil -c fetchall
bitbake libxkbui -c fetchall
bitbake libxaw -c fetchall
bitbake xbitmaps -c fetchall
bitbake openjpeg -c fetchall
bitbake fbida -c fetchall
bitbake terminus-font -c fetchall
bitbake glcompbench -c fetchall
bitbake lxdm -c fetchall
bitbake pangomm -c fetchall
bitbake x11vnc -c fetchall
bitbake openbox -c fetchall
bitbake assimp -c fetchall
bitbake numlockx -c fetchall
bitbake libvdpau -c fetchall
bitbake fontforge -c fetchall
bitbake fbgrab -c fetchall
bitbake qrencode -c fetchall
bitbake cairomm -c fetchall
bitbake gegl -c fetchall
bitbake babl -c fetchall
bitbake leptonica -c fetchall
bitbake xtscal -c fetchall
bitbake xdotool -c fetchall
bitbake libsexy -c fetchall
bitbake dietsplash -c fetchall
bitbake tesseract-lang -c fetchall
bitbake tesseract -c fetchall
bitbake packagegroup-fonts-truetype -c fetchall
bitbake xkbevd -c fetchall
bitbake xkbutils -c fetchall
bitbake xmessage -c fetchall
bitbake xrdb -c fetchall
bitbake xlsclients -c fetchall
bitbake xsetmode -c fetchall
bitbake xwd -c fetchall
bitbake xsetroot -c fetchall
bitbake bdftopcf -c fetchall
bitbake xkbprint -c fetchall
bitbake xrefresh -c fetchall
bitbake xlsatoms -c fetchall
bitbake sessreg -c fetchall
bitbake iceauth -c fetchall
bitbake xwud -c fetchall
bitbake xmag -c fetchall
bitbake xlsfonts -c fetchall
bitbake xclock -c fetchall
bitbake xfontsel -c fetchall
bitbake setxkbmap -c fetchall
bitbake xterm -c fetchall
bitbake twm -c fetchall
bitbake xgamma -c fetchall
bitbake xstdcmap -c fetchall
bitbake takao-fonts -c fetchall
bitbake xcursorgen -c fetchall
bitbake gphoto2 -c fetchall
bitbake libgphoto2 -c fetchall
bitbake gtkperf -c fetchall
bitbake ttf-pt-sans -c fetchall
bitbake source-han-sans-kr-fonts -c fetchall
bitbake ttf-arphic-uming -c fetchall
bitbake ttf-mplus -c fetchall
bitbake source-han-sans-jp-fonts -c fetchall
bitbake ttf-liberation -c fetchall
bitbake ttf-vlgothic -c fetchall
bitbake ttf-lohit -c fetchall
bitbake ttf-liberation-sans-narrow -c fetchall
bitbake source-han-sans-tw-fonts -c fetchall
bitbake ttf-lklug-14.20090803cvs.fc24 -c fetchall
bitbake ttf-gentium -c fetchall
bitbake source-han-sans-cn-fonts -c fetchall
bitbake ttf-wqy-zenhei -c fetchall
bitbake ttf-ubuntu-font-family -c fetchall
bitbake ttf-tlwg -c fetchall
bitbake ttf-dejavu -c fetchall
bitbake ttf-droid -c fetchall
bitbake ttf-inconsolata -c fetchall
bitbake ttf-sazanami -c fetchall
bitbake ttf-abyssinica -c fetchall
bitbake ttf-hunkyfonts -c fetchall
bitbake freeglut -c fetchall
bitbake xorg-sgml-doctools -c fetchall
bitbake xserver-common -c fetchall
bitbake directfb -c fetchall
bitbake directfb-examples -c fetchall
bitbake gimp -c fetchall
bitbake libsigc++-2.0 -c fetchall
bitbake libxml++ -c fetchall
bitbake glibmm -c fetchall
bitbake fakeroot-native -c fetchall
bitbake fakeroot -c fetchall
bitbake mm-common -c fetchall
bitbake toybox -c fetchall
bitbake distro-feed-configs -c fetchall
bitbake plymouth -c fetchall
bitbake dbus-daemon-proxy -c fetchall
bitbake llvm3.3 -c fetchall
bitbake llvm-common -c fetchall
bitbake eggdbus -c fetchall
bitbake usleep -c fetchall
bitbake proxy-libintl -c fetchall
bitbake packagegroup-boot -c fetchall
bitbake packagegroup-cli-tools -c fetchall
bitbake packagegroup-basic -c fetchall
bitbake sblim-sfc-common -c fetchall
bitbake logwatch -c fetchall
bitbake sgpio -c fetchall
bitbake libplist -c fetchall
bitbake fluentbit -c fetchall
bitbake liblockfile -c fetchall
bitbake rrdtool -c fetchall
bitbake can-utils -c fetchall
bitbake libsocketcan -c fetchall
bitbake canutils -c fetchall
bitbake flashrom -c fetchall
bitbake leveldb -c fetchall
bitbake corosync -c fetchall
bitbake sblim-sfcb -c fetchall
bitbake acpica -c fetchall
bitbake acpitests -c fetchall
bitbake scsirastools -c fetchall
bitbake testfloata -c fetchall
bitbake tipcutils -c fetchall
bitbake nicstat -c fetchall
bitbake md5deep -c fetchall
bitbake ddrescue -c fetchall
bitbake libgxim -c fetchall
bitbake libcec -c fetchall
bitbake efibootmgr -c fetchall
bitbake tcsh -c fetchall
bitbake dlm -c fetchall
bitbake lprng.C -c fetchall
bitbake indent -c fetchall
bitbake sysdig -c fetchall
bitbake efivar -c fetchall
bitbake acpitool -c fetchall
bitbake sblim-cmpi-devel -c fetchall
bitbake gnuplot -c fetchall
bitbake nana -c fetchall
bitbake libx86-1 -c fetchall
bitbake libqb -c fetchall
bitbake liblognorm -c fetchall
bitbake wipe -c fetchall
bitbake libdivecomputer -c fetchall
bitbake tmux -c fetchall
bitbake librelp -c fetchall
bitbake rsyslog -c fetchall
bitbake libfastjson -c fetchall
bitbake lsscsi -c fetchall
bitbake openwsman -c fetchall
bitbake subsurface -c fetchall
bitbake collectd -c fetchall
bitbake libmodbus -c fetchall
bitbake libmodbus -c fetchall
bitbake cmpi-bindings -c fetchall
bitbake libconfig -c fetchall
bitbake libwmf -c fetchall
bitbake haveged -c fetchall
bitbake konkretcmpi-native -c fetchall
bitbake konkretcmpi -c fetchall
bitbake uml-utilities -c fetchall
bitbake smartmontools -c fetchall
bitbake p7zip -c fetchall
bitbake lockfile-progs -c fetchall
bitbake tiptop -c fetchall
bitbake cfengine -c fetchall
bitbake cfengine-masterfiles -c fetchall
bitbake redis -c fetchall
bitbake zsh -c fetchall
bitbake openlmi-networking -c fetchall
bitbake openlmi-tools -c fetchall
bitbake openlmi-providers -c fetchall
bitbake openlmi-storage -c fetchall
bitbake hplip -c fetchall
bitbake jansson -c fetchall
bitbake polkit-group-rule-network -c fetchall
bitbake polkit-gnome -c fetchall
bitbake polkit -c fetchall
bitbake polkit-group-rule-datetime -c fetchall
bitbake logcheck -c fetchall
bitbake dash -c fetchall
bitbake liblogging -c fetchall
bitbake dialog-20160424 -c fetchall
bitbake t1lib -c fetchall
bitbake lcdproc -c fetchall
bitbake gtkmathview -c fetchall
bitbake iotop -c fetchall
bitbake pywbem -c fetchall
bitbake mozjs -c fetchall
bitbake rarpd -c fetchall
bitbake sblim-sfcc -c fetchall
bitbake zram -c fetchall
bitbake hexedit -c fetchall
bitbake libuio -c fetchall
bitbake iperf -c fetchall
bitbake bonnie++e -c fetchall
bitbake phoronix-test-suite -c fetchall
bitbake glmark2 -c fetchall
bitbake tiobench -c fetchall
bitbake libhugetlbfs -c fetchall
bitbake memtester -c fetchall
bitbake lmbench-a9 -c fetchall
bitbake tinymembench -c fetchall
bitbake sysbench -c fetchall
bitbake iozone3 -c fetchall
bitbake iperf3 -c fetchall
bitbake dbench -c fetchall
bitbake analyze-suspend -c fetchall
bitbake fio -c fetchall
bitbake cpuburn-neon -c fetchall
bitbake nbench-byte -c fetchall
bitbake telepathy-idle -c fetchall
bitbake telepathy-glib -c fetchall
bitbake libtelepathy -c fetchall
bitbake telepathy-mission-control -c fetchall
bitbake telepathy-python -c fetchall
bitbake rtorrent -c fetchall
bitbake lirc -c fetchall
bitbake libimobiledevice -c fetchall
bitbake libqmi -c fetchall
bitbake umip -c fetchall
bitbake libndp -c fetchall
bitbake krb5 -c fetchall
bitbake modemmanager -c fetchall
bitbake obex-data-server -c fetchall
bitbake openobex -c fetchall
bitbake zeromq -c fetchall
bitbake cppzmq -c fetchall
bitbake soft66 -c fetchall
bitbake thrift -c fetchall
bitbake ser2net -c fetchall
bitbake usbmuxd -c fetchall
bitbake libtorrent -c fetchall
bitbake hostapd -c fetchall
bitbake loudmouth -c fetchall
bitbake z -c fetchallix -c fetchall
bitbake irssi-rc1 -c fetchall
bitbake libmbim -c fetchall
bitbake gammu -c fetchall
bitbake libmtp -c fetchall
bitbake linuxptp -c fetchall
bitbake smstools3 -c fetchall
bitbake phonet-utils -c fetchall
bitbake r -c fetchallitmq-c -c fetchall
bitbake rfkill -c fetchall
bitbake libnet-rc3 -c fetchall
bitbake gst-plugin-bluetooth -c fetchall
bitbake bluez-hcidump -c fetchall
bitbake bluez4 -c fetchall
bitbake zeroc-ice -c fetchall
bitbake packagegroup-tools-bluetooth -c fetchall
bitbake mosh -c fetchall
bitbake wvdial -c fetchall
bitbake wvstreams -c fetchall
bitbake networkmanager -c fetchall
bitbake networkmanager-openvpn -c fetchall
bitbake gnokii -c fetchall
bitbake obexftp -c fetchall
bitbake pointercal -c fetchall
bitbake geos -c fetchall
bitbake orrery -c fetchall
bitbake gypsy -c fetchall
bitbake gypsy -c fetchall
bitbake libspatialite -c fetchall
bitbake geoclue -c fetchall
bitbake proj -c fetchall
bitbake gdal -c fetchall
bitbake gpsd -c fetchall
bitbake gpsd-machine-conf -c fetchall
bitbake foxtrotgps -c fetchall
bitbake navit -c fetchall
bitbake makedumpfile -c fetchall
bitbake minicoredumper -c fetchall
bitbake crash -c fetchall
bitbake ktap-module -c fetchall
bitbake ktap -c fetchall
bitbake gtkmm -c fetchall
bitbake libglade -c fetchall
bitbake gtkextra -c fetchall
bitbake vte9 -c fetchall
bitbake libunique -c fetchall
bitbake gtkhtml2 -c fetchall
bitbake gnome-doc-utils-stub -c fetchall
bitbake atkmm -c fetchall
bitbake fwts -c fetchall
bitbake gtest -c fetchall
bitbake gmock -c fetchall
bitbake opus-tools -c fetchall
bitbake l -c fetchallurn -c fetchall
bitbake libsdl2-image -c fetchall
bitbake libsdl-image -c fetchall
bitbake libass -c fetchall
bitbake libmms -c fetchall
bitbake libsdl2-mixer -c fetchall
bitbake libsdl-mixer -c fetchall
bitbake minidlna -c fetchall
bitbake id3lib -c fetchall
bitbake mplayer-common -c fetchall
bitbake mplayer2 -c fetchall
bitbake mpv -c fetchall
bitbake libmadb -c fetchall
bitbake esound -c fetchall
bitbake faad2 -c fetchall
bitbake libdvdread -c fetchall
bitbake yavta -c fetchall
bitbake v4l-utils -c fetchall
bitbake xpext-5 -c fetchall
bitbake xsp-8 -c fetchall
bitbake alsa-oss -c fetchall
bitbake audiofile -c fetchall
bitbake pavucontrol -c fetchall
bitbake libcdio -c fetchall
bitbake wavpack -c fetchall
bitbake cdrkit -c fetchall
bitbake libvpx -c fetchall
bitbake live555 -c fetchall
bitbake sound-theme-freedesktop -c fetchall
bitbake libopus -c fetchall
bitbake libmodplug -c fetchall
bitbake libmikmod -c fetchall
bitbake a2jmidid -c fetchall
bitbake jack -c fetchall
bitbake tclap -c fetchall
bitbake mpich -c fetchall
bitbake memstat -c fetchall
bitbake cppunit -c fetchall
bitbake jq -c fetchall
bitbake log4cplus -c fetchall
bitbake cunit-3 -c fetchall
bitbake ninja -c fetchall
bitbake lemon -c fetchall
bitbake lua -c fetchall
bitbake debootstrap -c fetchall
bitbake breakpad -c fetchall
bitbake giflib -c fetchall
bitbake vala-dbus-binding-tool -c fetchall
bitbake vala-dbus-binding-tool -c fetchall
bitbake cscopeb -c fetchall
bitbake pmtools -c fetchall
bitbake serialcheck -c fetchall
bitbake yajl -c fetchall
bitbake concurrencykit -c fetchall
bitbake tk -c fetchall
bitbake mcpp -c fetchall
bitbake iptraf -c fetchall
bitbake pm-qa -c fetchall
bitbake nodejs -c fetchall
bitbake android-tools-conf -c fetchall
bitbake android-tools.r37 -c fetchall
bitbake mercurial-native -c fetchall
bitbake uw-imapf -c fetchall
bitbake php -c fetchall
bitbake php -c fetchall
bitbake cloud9 -c fetchall
bitbake packagekit -c fetchall
bitbake ltrace -c fetchall
bitbake xerces-c -c fetchall
bitbake python-futures -c fetchall
bitbake python-cpuset -c fetchall
bitbake python-simplejson -c fetchall
bitbake python-pygobject -c fetchall
bitbake msr-tools -c fetchall
bitbake cgdb -c fetchall
bitbake libgee -c fetchall
bitbake icon-slicer -c fetchall
bitbake geany-plugins -c fetchall
bitbake geany -c fetchall
bitbake fribidi -c fetchall
bitbake ipc-run -c fetchall
bitbake libio-pty-perl -c fetchall
bitbake libdbi-perl -c fetchall
bitbake libdbd-mysql-perl -c fetchall
bitbake libubox -c fetchall
bitbake autoconf-archive -c fetchall
bitbake ctags -c fetchall
bitbake protobuf-c -c fetchall
bitbake protobuf -c fetchall
bitbake libedit-3.1 -c fetchall
bitbake luajit -c fetchall
bitbake ltp-ddt -c fetchall
bitbake packagegroup-sdk-target -c fetchall
bitbake dejagnu -c fetchall
bitbake glade3 -c fetchall
bitbake dt -c fetchall
bitbake bootchart -c fetchall
bitbake libxml-libxml-perl -c fetchall
bitbake libxml-filter-buffertext-perl -c fetchall
bitbake libxml-sax-writer-perl -c fetchall
bitbake libalgorithm-diff-perl -c fetchall
bitbake libmodule-pluggable-perl -c fetchall
bitbake libmodule-build-perl -c fetchall
bitbake libmodule-build-tiny-perl -c fetchall
bitbake libmodule-runtime-perl -c fetchall
bitbake libsub-exporter-progressive-perl -c fetchall
bitbake libcgi-perl -c fetchall
bitbake libcrypt-openssl-rsa-perl -c fetchall
bitbake libcrypt-openssl-random-perl -c fetchall
bitbake libclass-method-modifiers-perl -c fetchall
bitbake libimport-into-perl -c fetchall
bitbake libmoo-perl -c fetchall
bitbake libextutils-config-perl -c fetchall
bitbake libextutils-parsexs-perl -c fetchall
bitbake libextutils-helpers-perl -c fetchall
bitbake libextutils-installpaths-perl -c fetchall
bitbake libextutils-cppguess-perl -c fetchall
bitbake libcurses-perl -c fetchall
bitbake libproc-waitstat-perl -c fetchall
bitbake libauthen-sasl-perl -c fetchall
bitbake libtext-iconv-perl -c fetchall
bitbake libtext-diff-perl -c fetchall
bitbake libipc-signal-perl -c fetchall
bitbake adduser -c fetchall
bitbake libtest-harness-perl -c fetchall
bitbake librole-tiny-perl -c fetchall
bitbake libmime-types-perl -c fetchall
bitbake libio-stringy-perl -c fetchall
bitbake libio-socket-ssl-perl -c fetchall
bitbake libstrictures-perl -c fetchall
bitbake libhtml-parser-perl -c fetchall
bitbake libhtml-tree-perl -c fetchall
bitbake libdevel-globaldestruction-perl -c fetchall
bitbake libencode-locale-perl -c fetchall
bitbake libencode-perl -c fetchall
bitbake libnet-dns-perl -c fetchall
bitbake libnet-libidn-perl -c fetchall
bitbake libnet-ssleay-perl -c fetchall
bitbake libdbd-sqlite-perl -c fetchall
bitbake libdigest-hmac-perl -c fetchall
bitbake libdigest-sha1-perl -c fetchall
bitbake libcapture-tiny-perl -c fetchall
bitbake mime-construct -c fetchall
bitbake systemd-machine-units -c fetchall
bitbake libsrtp -c fetchall
bitbake libmediaart -c fetchall
bitbake libmediaart-2.0 -c fetchall
bitbake liboil -c fetchall
bitbake libmatroska -c fetchall
bitbake libebml -c fetchall
bitbake mkvtoolnix -c fetchall
bitbake rygel -c fetchall
bitbake libupnp -c fetchall
bitbake gupnp-tools -c fetchall
bitbake gupnp-av -c fetchall
bitbake gupnp-igd -c fetchall
bitbake gupnp-dlna -c fetchall
bitbake gssdp -c fetchall
bitbake gupnp -c fetchall
bitbake dvb-apps -c fetchall
bitbake tvheadend -c fetchall
bitbake oscam -c fetchall
bitbake schroedinger -c fetchall
bitbake dleyna-core -c fetchall
bitbake media-service-upnp -c fetchall
bitbake renderer-service-upnp -c fetchall
bitbake dleyna-connector-dbus -c fetchall
bitbake dleyna-server -c fetchall
bitbake dleyna-renderer -c fetchall
bitbake vlc -c fetchall
bitbake libdvdcss -c fetchall
bitbake gst123 -c fetchall
bitbake openal-soft -c fetchall
bitbake libiec61883 -c fetchall
bitbake libmusicbrainz -c fetchall
bitbake faac -c fetchall
bitbake vorbis-tools -c fetchall
bitbake libmpd -c fetchall
bitbake mpd -c fetchall
bitbake libdvdnav -c fetchall
bitbake alsa-equal -c fetchall
bitbake caps -c fetchall
bitbake opencore-amr -c fetchall
bitbake vo-amrwbenc -c fetchall
bitbake vo-aacenc -c fetchall
bitbake cdparanoia -c fetchall
bitbake fluidsynth -c fetchall
bitbake rtmpdump -c fetchall
bitbake sox -c fetchall
bitbake bigbuckbunny-1080p -c fetchall
bitbake bigbuckbunny-720p -c fetchall
bitbake tearsofsteel-1080p -c fetchall
bitbake bigbuckbunny-480p -c fetchall
bitbake libdvbpsi -c fetchall
bitbake libdc1394 -c fetchall
bitbake gst-plugins-good -c fetchall
bitbake gst-fluendo-mp3 -c fetchall
bitbake gstreamer -c fetchall
bitbake gst-ffmpeg -c fetchall
bitbake gst-meta-base -c fetchall
bitbake gst-rtsp -c fetchall
bitbake gst-openmax -c fetchall
bitbake gst-plugins-ugly -c fetchall
bitbake gst-fluendo-mpegdemux -c fetchall
bitbake gst-plugins-base -c fetchall
bitbake gst-plugins-gl -c fetchall
bitbake gst-plugins-bad -c fetchall
bitbake nativesdk-projucer -c fetchall
bitbake projucer-native -c fetchall
bitbake coriander -c fetchall
bitbake libao -c fetchall
bitbake libavc1394 -c fetchall
bitbake xbmc -c fetchall

